### ISSUE TITLE
切换到别的程序蚁剑就刷新 & 数据库查询列数过多时会挤在一起，并没有滚动条

### ISSUE THREAD

**Issue by imp0wd3r** [AntSwordProject/antSword#10]
只要切换到别的程序一下蚁剑就会刷新回主界面，之前打开的文件管理什么的也没了。

数据库查询的问题：
![screenshot from 2016-03-14](https://cloud.githubusercontent.com/assets/17606044/13734538/03ffbf5a-e9da-11e5-8b4d-bcc8e6c7e828.png)

列数太多无法显示了。

环境： Ubuntu 14.04

**Comment by antoor** [comment]
1. [程序窗口改变时,功能窗口关闭 #4](https://github.com/antoor/antSword/issues/4)
2. 后边可以考虑弄个滚动条

**Comment by Medicean** [comment]
v2.0.2 已解决。 #104
