### ISSUE TITLE
linux下上传文件功能乱码，请修改

### ISSUE THREAD

**Issue by Margular** [AntSwordProject/antSword#100]
linux下上传文件功能乱码，请修改

source/modules/filemanager/index.js:635

**Comment by Medicean** [comment]
@Margular  可否详细描述一下问题？

* 上传到目标机器的文件乱码？
* 点击上传时，弹出的本地文件选择框中的文件名乱码？

**Comment by Margular** [comment]
点击上传时，弹出的本地文件选择框中的文件名乱码
似乎是在linux下调用这个api会乱码，不懂nodejs，是不是你们全局变量里面设置了编码？导致我本地是UTF-8而你们设置了GB2312？或者字体库有要求？

**Comment by Medicean** [comment]
@Margular 这个问题是 electron 1.2.3 版本中的问题，之前在 https://github.com/AntSwordProject/AntSword-Loader/issues/4 提到过，后续整体框架升级才能修复这个问题。

**Comment by Margular** [comment]
这个就尴尬了，有没有替代方案？用着好难受啊

**Comment by Medicean** [comment]
已发布 v4.0.3 加载器，该版本加载器已经解决该问题。

https://github.com/AntSwordProject/AntSword-Loader/tree/4.0.3
