### ISSUE TITLE
蚁剑连接一句话图片失败

### ISSUE THREAD

**Issue by jazhLeo** [AntSwordProject/antSword#107]
使用 AntSword 测试 dvwa 文件上传漏洞的 high 级别时，使用 `cat shell.php >> xxx.png` 把一句话写入图片(测试图片使用百度logo，类型 png)，修改文件名为：xxx.php.png. 上传后提示成功。

在 AntSword 中尝试使用 http://xxx.xxx.xxx.xxx/dvwa/vulnerabilities/fi/?page=file:///var/www/html/dvwa/hackable/uploads/xxx.php.png 连接，无法连接。
手工测试该 URL POST 提交 `phpinfo();` 后页面成功显示 phpinfo() 的信息。
 
### 测试机环境
操作系统版本：macOS Mojave 10.14.2
安装 AntSword 版本：中国蚁剑 v2.0.2

### 服务器环境
kali linux `uname -a`：Linux kali 4.17.0-kali3-amd64 #1 SMP Debian 4.17.17-1kali1 (2018-08-21) x86_64 GNU/Linux
php版本：7.2.9
dvwa 版本： Version 1.10 *Development*（dvwa about 里给出的，不知道对不对，于2018年12月1x日从官方网站下载）

附手工图片：
![image](https://user-images.githubusercontent.com/16217983/50239293-c697f480-03fc-11e9-8df3-7b8835da3aa2.png)

**Comment by jazhLeo** [comment]
非常感谢耐心的解答， 犯了个新手错误感觉很愧疚。 
再问一个问题，能不能显示的添加一个 Log 或者说 Error Log 界面。 
这样有时候更方便定位错误 😁。

**Comment by Medicean** [comment]
打开开发者控制台，在 console 选项卡下输入 `antSword["logs"]`

**Comment by sunozil** [comment]
这个问题困扰了我一整天  没想到这里  回答的很详细 感谢感谢

**Comment by sunozil** [comment]
提问的也很清楚

**Comment by yarkable** [comment]
这个回答我半年前就看到了，当时没当一回事，今天搞了两个小时，心态炸了

**Comment by sunozil** [comment]
> 这个回答我半年前就看到了，当时没当一回事，今天搞了两个小时，心态炸了

没事 这样才记得清楚嘛
