### ISSUE TITLE
新的建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#109]
- [ x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x ] 这是一个新功能的建议
- [x ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [x ] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

1.建议在目录列表的右键菜单里加入“在浏览器中打开”这一选项。
目前来说你如果上传了一个新的文件，你想要在浏览器中查看，你需要先返回首页，再编辑信息，然后复制网站域名，然后再返回去复制路径，然后再复制文件名称，然后把他们拼到一起粘贴到浏览器中，这样是比较麻烦的。

2.建议添加“上传被控端”功能。
有时候需要放置多个shell文件，如果可以事先把被控端的代码放入到蚁剑里，然后在shell目录里点击右键上传被控端，被控端的名称可以随机(防止被猜出)，然后自动把上传的shell地址保存。这个功能在xise里做得比较好，虽然xise是个黑帽工具，但是依旧有一些可以参考的地方。

3.建议添加shell的时候增加快速模式
蚁剑的功能是非常强大的，并且是可以自定义的。但是就像安装软件的时候不是所有人都喜欢非常细化的定义，有时候可能只是想尽快用上软件。蚁剑在添加数据的时候可以借鉴菜刀，自动识别后缀，并且编码器可以增加一个“循环测试”按钮。也就是说default连接不上试试random，random不行试试base64，依次循环。因为如果不这样的话在遇到waf的时候，人工一个个来回在设置中换的话会很麻烦。

4.文件复制选项
对于文件复制的话可以设置成为点击复制文件后默认把文件的绝对路径复制到剪切板里，这样对于提权测试的时候会非常方便。

还望采纳，谢谢！
希望蚁剑越做越好。

**Comment by Medicean** [comment]
感谢提的建议，逐条回复吧。

1. 非法好的提议，未来会实现这一功能。但是在实现起来能够预测到会有一堆特殊问题需要处理，比如说，目标网站用了 rewrite 方式, JSP 网站的 `WEB-INF` 目录无法通过 web 访问等问题，不知你有什么好的可实施的方案。

2. 持久维持「后门」与我们的初衷相违背，不会在核心中增加该功能。个人认为在实际授权测试当中并不会用到该功能，如果特别需要的话，建议可以自己写插件来实现。

3.非常好的体验建议，一直没提上日程去做这个东西，已经在开始做了一部分(900d18f)。我的想法是添加 Shell 时再添加一个「测试连接」按钮。

4. 复制文件路径这个功能如果变成「在此处打开终端」自动打开虚拟终端，并且 cd 到该目录下？

**Comment by yzddmr6** [comment]
再增加一点
6. 建议点击创建新文件之后自动跳转到编辑页面
不然的话还要另外去找这个新创建的文件，如果当前目录文件比较多的话就比较麻烦

**Comment by yzddmr6** [comment]
再增加一点
8 增加返回网站根目录功能
现在只有一个返回主目录，也就是返回shell所在目录按钮。可以增加一个返回网站根目录按钮，更加方便。

**Comment by Medicean** [comment]
@yzddmr6 建议一个 issue 里面只讲一个点，不要提太多。

**Comment by yzddmr6** [comment]
好的👌
