### ISSUE TITLE
add english docs

### ISSUE THREAD

**Issue by hsen-dev** [AntSwordProject/antSword#11]

**Comment by antoor** [comment]
Given my English is not very good, it may take some time! U_U~

**Comment by hack2012** [comment]
我顶，后期完善了以后再增加英文文档吧，要不老外会说我们中国人开发的东西不太严谨。

**Comment by antoor** [comment]
@hack2012 哈哈，是这样打算的。因为一开始就设计了多语言化，是不是感觉野心很大？

**Comment by hack2012** [comment]
就应该这样，等你的做的更好了，我会在我的博客上面给你推荐一把的。http://www.waitalone.cn/

**Comment by GalvinGao** [comment]
May I join this project? xD

**Comment by GalvinGao** [comment]
@antoor 我想编english doc xD

**Comment by Medicean** [comment]
使用自带的翻译功能 https://www.yuque.com/antswordproject/antsword/
