### ISSUE TITLE
数据库编码无法保存，另外mysql数据编码实现错误

### ISSUE THREAD

**Issue by Twi1ight** [AntSwordProject/antSword#110]
数据库编码，不管怎么设置，保存后还是恢复到UTF-8（只测试了php+mysql的情况）
另外，mysql数据库内容是中文时，存在乱码，原因是php代码模板实现写错
antSword/source/core/php/template/database/mysql.js
antSword/source/core/php/template/database/mysqli.js
这两个文件的最后一个query模板中，设置编码的语句写漏了$_POST
`@mysql_query("SET NAMES ${arg6}");` 
这句代码应该是`@mysql_query("SET NAMES ".$_POST["${arg6}"]);`

**Comment by Twi1ight** [comment]
另外，我不想用加载器，`npm build`的时候报错，说AntSword命令不存在，这怎么解决

**Comment by Medicean** [comment]
感谢反馈。

使用加载器主要是出于以下几个方面考虑：

1. 版本不一致会出各种问题, 核心代码均使用 electron v1.2.3 编写, electron 版本不一致时无法保证正常运行
2. build 方式修改源代码时需要重新编译，使用起来不够灵活

从 v2 开始全面使用 Loader 的方式，如果实在想用可自行修改源代码。

AntSword命令不存在的原因可以修改 package.json 里 script 部分的代码 https://github.com/AntSwordProject/antSword/blob/master/package.json#L17
