### ISSUE TITLE
JSP的bug

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#111]
- [ x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [ x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ x] 我使用的操作系统是 ***Windows*** 10+
- [x ] 我使用的是 64 位操作系统

### shell 连接 Bug

1. 服务端操作系统
win10 
2. 服务端shell代码

蚁剑自带的 jsp 跟jspx

三种编码都试过了

3. 服务端环境配置

菜刀的jsp一句话可以连接
换成蚁剑的就连接不了了
![caidao](https://user-images.githubusercontent.com/46088090/50413099-a1194980-0847-11e9-8a29-ae00891201c0.jpg)

![ant](https://user-images.githubusercontent.com/46088090/50413120-d756c900-0847-11e9-914a-6cc96e84451f.jpg)

可能跟这个有关？
![cmd](https://user-images.githubusercontent.com/46088090/50413149-12f19300-0848-11e9-8d8e-62523c3a2d82.jpg)

4. 客户端连接配置

{"category":"default","url":"http://******/config.jsp","pwd":"daoen","note":"","type":"custom","ip":"******","addr":"四川省绵阳市 电信","encode":"UTF8","encoder":"base64","httpConf":{"body":{},"headers":{}},"otherConf":{"command-path":"","filemanager-cache":1,"ignore-https":0,"request-timeout":"10000","terminal-cache":0,"upload-fragment":"500"},"ctime":1545714158750,"utime":1545714158750,"_id":"cRRIOQ8QeFhM3he6"}

**Comment by Medicean** [comment]
关于 jsp 的 shell 官方仓库只提供样例 shell，在具体使用过程中需要使用者自行根据实际情况适当修改源代码。你可以查看一下 shell 中的使用说明。

有关编码器的问题，需要修改此处：

https://github.com/AntSwordProject/antSword/blob/master/shells/jsp_custom_script_for_mysql.jsp#L46

命令执行所用到的 shell 路径可以自己在编辑 Shell 配置的其它配置里面自行设置。

**Comment by yzddmr6** [comment]
好的，但是在我测试的过程中有不少linux的shell都出现了403这个问题，似乎这不只是一个个例。如果许多都存在这个问题的话可能官方推出一个兼容更好的shell会更好。或者我把shell的具体信息通过邮件发给你？

**Comment by yzddmr6** [comment]
好的

**Comment by yzddmr6** [comment]
刷src。。。不是某产

**Comment by yzddmr6** [comment]
感谢回复！问题已经解决
