### ISSUE TITLE
请问如何修改标签页标题ip为域名

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#113]
![1](https://user-images.githubusercontent.com/46088090/50500663-d6af7400-0a8d-11e9-907e-27333c107b23.jpg)

8.   这也算是个建议吧hhhhh
请问如何把标题中的ip换为域名呢
因为有时候打开的标签页多了就不知道哪个ip对应哪个域名了
或者打开同一个ip上的不同站点的时候就容易搞混
建议把标题换成域名这样容易区分
如果不打算修改的话麻烦指教一下如何修改哈，我把自己的改一下

**Comment by yzddmr6** [comment]
但是这样显示出来的是shell的地址，如何让他只显示主域名呢

**Comment by Medicean** [comment]
```
> url='http://www.example.com:8081/test/ant.php?a=1&b=2#demo'
'http://www.example.com:8081/test/ant.php?a=1&b=2#demo'
> /https?:\/\/(.+?)\//.test(url)
true
> RegExp.$1
'www.example.com:8081'
>
```

**Comment by yzddmr6** [comment]
emmmmm我的意思是怎么具体在代码中修改

**Comment by ViCrack** [comment]
`    tabbar.addTab(
      `tab_filemanager_${hash}`,
      `<i class="fa fa-folder-o"></i> ${opts['url'].match(/https?:\/\/(.+?)\//)[0]}`,
      null, null, true, true
    );`

**Comment by yzddmr6** [comment]
> ` tabbar.addTab(`tab_filemanager_${hash}`, ` ${opts['url'].match(/https?://(.+?)//)[0]}`, null, null, true, true );`

感谢! 但是要考虑到转义字符'\'
把原句改为`<i class="fa fa-folder-o"></i> ${opts['url'].match(/https?:\/\/(.+?)\//)[0]}`,即可
