### ISSUE TITLE
请求新功能-对webshell 响应数据进行编码

### ISSUE THREAD

**Issue by jinyu00** [AntSwordProject/antSword#114]
现在用蚁剑可以使用 编码器 编码 蚁剑发送给 webshell 的数据， 但是 webshell 的回显是明文的， 可不可以考虑加入对回显数据的编码功能，类似于 [利用动态二进制加密实现新型一句话木马之客户端篇](https://xz.aliyun.com/t/2799)

**Comment by Medicean** [comment]
已经在未公开的版本里做了双向编码了。考虑到对现有的编码器的兼容性，暂时没有在 2.x 版本中体现的计划，后续测试差不多了会做。

**Comment by Medicean** [comment]
目前已经对 PHP、PHP4 类型返回包进行了支持，其它后续研究后再实现
