### ISSUE TITLE
标签的Bug与建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#126]
BUG:
应该算是个bug吧   我发现在拖动列表标签大小的时候
![111](https://user-images.githubusercontent.com/46088090/52159639-0df2ef80-26e2-11e9-9546-21060df27459.JPG)

其他地方的标签大小都可以调节,但是"网站备注"标签的大小是不能调节的
希望在下个版本能够修复

新的建议:

可不可以在"ip地址"后面增加一个"可写路径"栏跟"系统型号"栏
系统型号如 windows 2008  , linux centos 6
可写路径如 D:/wwwroot/
这样就不用点开shell就知道更多简略的信息了

**Comment by Medicean** [comment]
此做法会让 ShellManager 与 FileManager 耦合过多，并且意义不大，如果需要实现可以自已修改
