### ISSUE TITLE
编码器保存功能不奏效

### ISSUE THREAD

**Issue by K4ngx** [AntSwordProject/antSword#135]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [x] 我使用的操作系统是 ***Windows*** 7

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

在编写一个新的编码器并初次保存后，该编码器可正常使用。但是在后续对编码器进行修改编辑并保存时，虽然显示保存成功，然而经过多次的测试和wireshark的抓包分析，结果是我对该编码器所做的后续修改都没有奏效。

**Comment by Medicean** [comment]
首先定位一下问题所在

1） 查看 antData/encoders/ 下面你编辑保存的编码器文件，是不是真的保存成功了

2）如果保存成功了，重新 reload 程序，可以在开发者控制台里面调试你的编码器代码，看下是不是编码器代码的问题

**Comment by K4ngx** [comment]
测试了一下，发现编码器初次的保存是不需要reload便能生效的，而后续做的修改的确保存成功了，但是需要reload才能生效。请问对编码器后续发生的修改是否可以实现立即生效而不需要reload呢。

**Comment by Medicean** [comment]
用的都是同一个方法

https://github.com/AntSwordProject/antSword/blob/6cdd78eb86b3cb16f771e876c92f6f73870e03de/source/modules/settings/encoders.js#L240-L245

具体为何产生这样原因，我这边复现不出来，你那边能打个断点追一下原因吗？

**Comment by K4ngx** [comment]
经过调试发现问题在于编码器的require引入。nodejs require存在缓存机制，无法检测到文件变化。因此问题不在于编码器是否是第一次保存；而在于该编码器若被require引入过一次，后续的内容改变皆无法生效，返回的依然是第一次引入的文件内容。

https://github.com/AntSwordProject/antSword/blob/6cdd78eb86b3cb16f771e876c92f6f73870e03de/source/core/base.js#L183-L187

因此需要在每次重复引用之前删除对应缓存。在186行前插入如下代码即可

```javascript
delete require.cache[require.resolve(`${enc}`)];
```

或者也可以尝试在编码器内容发生改变时，删除该编码器的require缓存（也许这个方法更好）。

**Comment by Medicean** [comment]
thx 👍
