### ISSUE TITLE
可以增加批量导入的功能吗

### ISSUE THREAD

**Issue by 9tail123** [AntSwordProject/antSword#137]
希望可以从txt之类的文件里导入shell

**Comment by Medicean** [comment]
目前可通过`Shell配置导入`插件导入数据，如果需要自己需要定制化，可直接向数据文件 `antData/db.ant` 按照格式写入数据。

**Comment by virink** [comment]
@9tail123 
插件已上架
https://github.com/AntSword-Store/as_plugin_import_shell_from_csv
欢迎品尝
