### ISSUE TITLE
windows平台下使用报错？什么瞄

### ISSUE THREAD

**Issue by windy-purple** [AntSwordProject/antSword#138]
运行系统：win10 x64，
node版本：10.15.3，
electron版本：4.1.0，
编译运行报错：
![捕获](https://user-images.githubusercontent.com/35889837/55246803-f7e85200-5280-11e9-87ea-f09de259406d.PNG)

**Comment by Medicean** [comment]
使用官方加载器，并不是源生的 electron 就能用。
参考文档：https://doc.u0u.us/zh-hans/getting_started/get_antsword.html
