### ISSUE TITLE
关于全局设置的建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#139]
aha,没错我又来提建议了

蚁剑真的做的越来越好了,现在已经不想用菜刀了

这次的建议是关于一些全局设置的建议

就像当前的系统设置中 ->默认设置->文件打开方式一样, 可以在设置中让用户自定义全局变量例如:
shell默认密码  
默认UA请求头  
php默认编码器选哪一个 aspx的默认编码器选哪一个 等
标签页名字采用ip的方式还是采取域名的方式
等等一些 
这样的话用起来会更加方便,特别是编码器这一项,基本上都不会选择default,把它放在所有shell的默认选项可能就不是一个好的做法.

**Comment by Medicean** [comment]
Good idea，已经在计划列表中了

**Comment by Medicean** [comment]
数据管理 相关的默认配置已经在 v2.1.x 开发版本中加入， 如果可以麻烦一同参与 #162 中的测试内容

**Comment by yzddmr6** [comment]
好的  可是开发版本在哪儿呢

**Comment by B0y1n4o4** [comment]
代理建议：代理的功能，可以给每个shell配置编辑增加一个，在面对不同的shell需要的代理需求不一样，又得重新修改全局代理模式，重载AS

**Comment by Medicean** [comment]
> 代理建议：代理的功能，可以给每个shell配置编辑增加一个（个别有需求设置不同的代理，覆盖全局的代理），在面对不同的shell需要的代理需求不一样，又得重新修改全局代理模式，重载AS

这个建议在目前架构上实现起来有些麻烦，起了新的 issue，未来再考虑实现。
