### ISSUE TITLE
新功能建议:多文件下载

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#140]
当前版本的蚁剑在shell里面选中多个文件的时候支持多文件删除,  如果能够支持多文件下载就更好了

**Comment by sstszwl3** [comment]
同求多文件下载，现在几乎没有支持多文件下载的。有没有人能提供个能多文件下载的，不胜感激！

**Comment by virink** [comment]
@yzddmr6 @sstszwl3 
git checkout feature/multidownload
试试吧

ps. @Medicean 表哥，坑我又挖了一点，你抽时间填一下？

**Comment by Medicean** [comment]
done

**Comment by yzddmr6** [comment]
✌✌✌
