### ISSUE TITLE
关于CUSTOMER功能

### ISSUE THREAD

**Issue by RoyTse** [AntSwordProject/antSword#141]
- [x] 我是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至(https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [ ] 我使用的是 64 位操作系统

---

## 新功能建议

- [ ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [ ] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

管理shell的时候 连接选项有一个custom选项，经过抓包发现只是发送一个A。永远没办法成功使用。请问我该如何编辑我自己的custom，又该放在哪个位置？

**Comment by RoyTse** [comment]
为什么看不到新功能描述后面的具体问题- -
我想知道如何编辑custom 然后该放在项目的什么位置？
如果可以的话 希望给一个实例
谢谢！

**Comment by Medicean** [comment]
参考:
https://github.com/AntSwordProject/antSword/blob/master/shells/

**Comment by RoyTse** [comment]
谢谢！原来是这个意思。没注意到shell实例里面的custom。不好意思

想自定义成直接执行命令的交互
看来还是要从插件入手

**Comment by Medicean** [comment]
你这个需求可以参考一下 「执行代码」 这个插件：

https://github.com/AntSword-Store/ExecScript

**Comment by RoyTse** [comment]
这个插件昨天参考过了，可能这个插件更应该命名为自定义执行脚本代码。
不符合我的使用场景。
我的场景如下，服务器上有一个类似于<?php system($_POST[c]);?>的文件。
我想用antsword直接管理这样的shell。

我刚刚经过研究觉得这个应该属于语言模板开发，我已经按照你写好的几个语言模板在尝试新增bash模板…

**Comment by RoyTse** [comment]
请问语言模板里面类似于filemanager.js的文件。我该如何获得arg1的value，而不是arg1的key。

比如dir功能，我想直接改成`ls -al arg1`。
由于我本身并不会nodejs，尝试看了base.js index.js。还是没搞清。

**Comment by Medicean** [comment]
参考：

https://github.com/AntSwordProject/antSword/blob/414d62d7bb3e258c564b49bf6bae7e2edd791928/source/core/custom/template/filemanager.js#L5-L15

**Comment by RoyTse** [comment]
谢谢你的耐心指教，我已经大致实现了demo
但是在多参数时遇到了问题。
例如copy的实现我这样写的
copy:{
_:' cp #{path} #{target}'
}

实际payload构造的时候 只会初始化target，不会初始化path。这应该是一个bug
