### ISSUE TITLE
PHP下载功能不附带自定义请求信息的BUG

### ISSUE THREAD

**Issue by RoyTse** [AntSwordProject/antSword#142]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题

---

## 报告 Bug

- [x] 我使用的操作系统是 ***macOS*** 10+
- [x] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [x] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [x] 我使用的操作系统是 ***Arch*** GNU/Linux
- [x] 我使用的操作系统是 ***Other*** GNU/Linux
- [x] 我使用的操作系统是 ***Windows*** 10+

---

- [x] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

---

## 新功能建议

- [x] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [x] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### shell 连接 Bug

2. 服务端shell代码

4. 客户端连接配置

**Comment by RoyTse** [comment]
问题应该出在/source/modules/filemanager/index.js第590行。没有使用this.core.request

**Comment by RoyTse** [comment]
\source\core\base.js里面的download函数第289行，url:this.__opts__['url']
运行到这里的时候 headers没有传进到ipcRenderer

**Comment by Medicean** [comment]
是的，这里没和request用同样的方式处理
