### ISSUE TITLE
jsp的bug

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#143]
连接测试的时候可以
![image](https://user-images.githubusercontent.com/46088090/55670831-8bda9f00-58bb-11e9-9b93-55ef0dc86d27.png)

但是打开的时候就错误
![image](https://user-images.githubusercontent.com/46088090/55670834-9b59e800-58bb-11e9-9c24-c23a81ecf574.png)

抓包出现这个报错
![image](https://user-images.githubusercontent.com/46088090/55670826-82513700-58bb-11e9-96a0-ee663dd557f4.png)

**Comment by Medicean** [comment]
这个你得自己处理空指针问题, 所给的示例 shell 只是一个 demo

**Comment by yzddmr6** [comment]
emmmm好的吧
只是在测试过程中发现官方给的demo很多环境都不兼容 有时候还会出现403错误
兼容性最好的还是2011版的菜刀的jsp shell 
如果能参考那个改进一下使其兼容性提高也是极好的
感谢回复
