### ISSUE TITLE
复制 Shell URL

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#144]
建议在目录列表增加右键: 复制shell地址 功能
一般来说如果shell连接不上的话我会首先把它放在浏览器里看是不是404了或者500报错怎么样之类的,这就需要复制shell的地址. 在当前的情况下是要先点开 编辑信息然后再复制shell地址 确实不是很方便  如果能够右键直接增加复制功能将会方便很多

**Comment by Medicean** [comment]
建议直接用插件来实现，参考 : https://mp.weixin.qq.com/s/xdvHBWT2VuwYG1Obn7xLIw

**Comment by yzddmr6** [comment]
emmm我觉得这个应该是大多数人都有这个需求吧，如果在主体加上会好一点

**Comment by Medicean** [comment]
或许可以讨论一下，看看是否真的有必要在主体中增加

**Comment by ylqingf** [comment]
我觉得可以有

**Comment by Medicean** [comment]
上架了一个插件 「[复制URL](https://github.com/AntSword-Store/as_copyurl)」, 可以先试用一下

**Comment by virink** [comment]
放在主体吧、放在View Site后面

**Comment by naivekun** [comment]
放在主体+1
