### ISSUE TITLE
aspowershell 的问题

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#148]
![image](https://user-images.githubusercontent.com/46088090/56178557-47769e00-6035-11e9-99c4-b2ab497871b0.png)

![image](https://user-images.githubusercontent.com/46088090/56178580-5eb58b80-6035-11e9-92ec-85f73c33c806.png)

请教一下为什么设置powershell模式之后执行一个whoami后面就报错了? 前面的pwd也变了
emmm还有就是更新过后的版本aslistcmd里面好多被转义的<br>换行符....看起来不太美观

**Comment by Medicean** [comment]
看你这个报错的样子，好像是找不到 驱动器

**Comment by yzddmr6** [comment]
经过测试其他的都没有问题
emmmmm玄学
关了吧
