### ISSUE TITLE
Search Crash

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#157]
![image](https://user-images.githubusercontent.com/46088090/56709894-3c6aee80-6756-11e9-9018-e025b2d31302.png)
输入一个 \  蚁剑就会直接崩溃卡死
环境 : win新版本加载器

**Comment by Medicean** [comment]
搜索的时候用了正则表达式，如果表达式输入的错误的话(比如: `(a`)，就会 throw Exception.

修复方案如下：尝试将输入 build 成正则表达式，如果出错的话，就把所有的正则表达式字符全部转义。
