### ISSUE TITLE
新插件建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#158]
能不能推出一个检测目录权限的插件  或者说直接加入主体功能
功能包括 检测当前目录是否可写  如果当前目录不可写检测根目录下可写目录
是否支持asp php aspx jsp等其他格式的脚本(重要)
但是目前的插件只能在shell list列表里右键执行  如果按照我说这样的话应该是要加进主体功能里了
这样我可以在任意目录里右键  检测权限
如果能把检测到的可写目录放到shell list的更新时间后面一栏就更好了  这样既可以分出来win还是linux  也可以查看是否可写

其实这个想法是xise最先实现的,作者有空了可以研究一下,确实非常好用

假如说php权限很低的话如果检测到支持jsp或者aspx的话权限一般比较大  提权的时候就比较方便

**Comment by Medicean** [comment]
目录和文件权限从 v1 开始就已经在文件管理中支持，无需重复开发

**Comment by yzddmr6** [comment]
我的意思不是可不可以检测  我的意思是能否呈现给用户
假如一个网站只允许某些二级甚至三级目录可写 其他目录都不可写  你虽然可以看到他的属性
但是作为用户 需要不断一个个翻才能知道
比如织梦很多是/data/session可写  这是因为这个cms大家都很熟悉
但是还有很多网站你不清楚他的哪些可以写哪些不可以  
二级三级目录翻起来很麻烦 这也是我在实际中遇到的问题
如果可以用插件遍历  并且输出哪些可写哪些不可写会比较方便.
