### ISSUE TITLE
复制建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#159]
![image](https://user-images.githubusercontent.com/46088090/56730962-d9944a00-678b-11e9-840b-20a5ab92e821.png)

有时候编辑完文件想直接复制名字  但是目前的版本不可以
建议改成能够支持复制红框内的文字

**Comment by Medicean** [comment]
这个功能意义不大，后续反馈较多时再行考虑。

**Comment by yzddmr6** [comment]
我的意思是只用把他这一栏的标签改成可以选中就行了.....
然后ctrl c
