### ISSUE TITLE
测试默认设置是否有xss漏洞

### ISSUE THREAD

**Issue by Medicean** [AntSwordProject/antSword#160]
主要代码是这里：

https://github.com/AntSwordProject/antSword/blob/0958eb60122958cb433646e94d772c2cc3954188/source/modules/settings/adefault.js#L370-L375

表格中显示时如果用 `antSword.noxss` 处理，在显示时会有二次转义，由于 sql语句中需要一些特殊符号，所以此处并未对输入进行过滤。

需要测试该处是否会引起 self-xss.

**Comment by yw9381** [comment]
测试了整个书签在数据库这一块的东西，对于前端都进行了实体编码，没法XSS
