### ISSUE TITLE
目录建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#161]
![image](https://user-images.githubusercontent.com/46088090/56858997-e779e300-69b6-11e9-851f-5be37e1cc18b.png)

现在可以很快切换到网站根目录
能否增加一个按钮可以迅速切换到shell所在目录呢  方便shell的删改
如果书签可以实现的话还请麻烦告知一下如何修改

**Comment by Medicean** [comment]
点 「主目录」或者自己去 Shell 目录加个书签

**Comment by yzddmr6** [comment]
我说错了..........现在的"主目录"是直接到shell目录......
能不能加个按钮直接到网站根目录呢
