### ISSUE TITLE
搜索数据能否支持搜索ip

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#165]
搜索功能能否在下个版本中支持搜索域名的ip

**Comment by Medicean** [comment]
本来就支持的

![image](https://user-images.githubusercontent.com/6082020/57207544-030d6b00-7001-11e9-8ac5-25cc3339effe.png)

**Comment by yzddmr6** [comment]
可能我的表述不清楚
![image](https://user-images.githubusercontent.com/46088090/57207652-96df3700-7001-11e9-9404-a0e5f0b4435d.png)
![image](https://user-images.githubusercontent.com/46088090/57207659-a3fc2600-7001-11e9-8fac-e7ef9fd09666.png)

这就找不到了

**Comment by Medicean** [comment]
all 的意思是 下面3个选项任意一个匹配

**Comment by yzddmr6** [comment]
感谢
