### ISSUE TITLE
又来一发 XSS 安全隐患

### ISSUE THREAD

**Issue by ViCrack** [AntSwordProject/antSword#166]
之前随便看到的

比如上架的插件PortScan

因为完全只是简单的信任了服务端的返回数据, 无编码直接就显示了, 所以可以伪造返回的数据
![6546546546](https://user-images.githubusercontent.com/18179821/57231655-85bc1780-704d-11e9-9277-d1485f6edc3c.jpg)

就这样吧
你懂的

除了主程序要检查之外, 其他一些上架的Plugin也要进行检查

**Comment by Medicean** [comment]
这个应该是修改了本地的 payload 或者是 服务端专门针对 portscan 返回在中间件层面上对返回包做了修改才会有这种情况。还是感谢提出。
