### ISSUE TITLE
#150 修复不完善

### ISSUE THREAD

**Issue by l0ca1** [AntSwordProject/antSword#167]
### Bug 详细描述
漏洞点：https://github.com/AntSwordProject/antSword/blob/master/source/modules/filemanager/files.js#L553

原因：
在 https://github.com/AntSwordProject/antSword/blob/b4d8257c6177260912d9e5455eb001e9a6900ce9/source/modules/filemanager/index.js#L123
![image](https://user-images.githubusercontent.com/23295562/57282576-ebf17a80-70df-11e9-9679-81089ff49f41.png)
上一次#150修复在 new File 构造函数中，但file.parse 又对路径值进行了重新复制，通过直接修改shell所在地址的部分为xss语句，造成相同影响。

---

## 新功能建议
对parse中的manager.path做noxss处理

**Comment by Medicean** [comment]
能否在邮件里提供一下详细的复现过程？ Medici.Yan@gmail.com

**Comment by l0ca1** [comment]
这个地方我应该弄错了，麻烦了

**Comment by Medicean** [comment]
有空可以再找找，可能还有隐藏的没发现的
