### ISSUE TITLE
https ENOTFOUND 错误

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#170]
![1a](https://user-images.githubusercontent.com/46088090/57670852-b26ec100-7643-11e9-8e5b-d2d42b0fead8.png)

连接https的老是报这个错为什么呢

**Comment by yzddmr6** [comment]
一会儿好了一会儿又报错.......

**Comment by yzddmr6** [comment]
我发现了  只要进行什么新的操作  比如说转到一个新的目录他就会先报一遍这个错误
但是你重新点一次就好了
希望以后能够修复....不然来回点两次比较麻烦....

**Comment by Medicean** [comment]
「编辑数据」-> 「其它设置」 勾上「忽略HTTPS证书」试试

**Comment by Medicean** [comment]
查了一下 ENOTFOUND 错误：

> Error: getaddrinfo ENOTFOUND http://xx.yy.com
> 
> 解决方法：在 `node.js` 中使用 http 或者 https 发送请求的时候 host 不要带 `http://` 或者 `https://`,直接写`xx.yy.com` 即可

看一下你自己有没有在 Shell 配置里加了 `Host` 这个头，默认请求的时候`Host`头是不会带 `http://` 这样的头的

**Comment by yzddmr6** [comment]
我设置过忽略证书了,可是有时候还会出现这个问题
我没有设置host这个头
算了  小问题  多点几下就多点几下吧....
