### ISSUE TITLE
jspshell for mysql  base64编码器数据库报错

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#171]
jsp for mysql  使用base64编码器
![image](https://user-images.githubusercontent.com/46088090/57671377-214d1980-7646-11e9-8e27-833c069fe8ad.png)

default就没有问题
![image](https://user-images.githubusercontent.com/46088090/57671403-388c0700-7646-11e9-96f4-e97c70adc92c.png)

**Comment by Medicean** [comment]
https://github.com/AntSwordProject/antSword/blob/master/shells/jsp_custom_script_for_mysql.jsp#L45-L52
