### ISSUE TITLE
jsp for mysql 数据库导出没反应

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#172]
正常查询后导出按钮点击后没反应
![image](https://user-images.githubusercontent.com/46088090/57671646-3a09ff00-7647-11e9-8085-ca0783676319.png)

**Comment by Medicean** [comment]
在 ASP 和 Custom 两个数据库管理中没有引入 dialog 模块引起的

**Comment by yzddmr6** [comment]
辛苦了
