### ISSUE TITLE
jsp+oracle+default模式显示找不到驱动

### ISSUE THREAD

**Issue by supermisscat** [AntSwordProject/antSword#174]
在default的模式，连接的时候找不到驱动 
![image](https://user-images.githubusercontent.com/16932404/57828004-6440f580-77dc-11e9-87a1-a5a7a17808b8.png)
base64模式的话 就可以找到驱动连接正常
![image](https://user-images.githubusercontent.com/16932404/57828119-e3362e00-77dc-11e9-98ed-45ffefce93ea.png)

**Comment by Medicean** [comment]
取决于你的 jsp 代码里面设置的：

https://github.com/AntSwordProject/antSword/blob/master/shells/jsp_custom_script_for_oracle.jsp#L36

**Comment by supermisscat** [comment]
> 取决于你的 jsp 代码里面设置的：
> 
> https://github.com/AntSwordProject/antSword/blob/master/shells/jsp_custom_script_for_oracle.jsp#L36

是的，问题是服务端跟客户端我都选择了对应的编码的。但是base64访问是有驱动连接成功，default显示找不到class连接失败。然而其他功能正常的使用的。

**Comment by Medicean** [comment]
我测试了一下，没复现问题，配置这里应该是4行，你可以抓个包看看

```
ant=N&z0=&z1=oracle.jdbc.driver.OracleDriver%0Ajdbc%3Aoracle%3Athin%3A%40127.0.0.1%3A1521%2Ftest%0Auser%0Apassword
```

`%0A` 是换行符

**Comment by supermisscat** [comment]
> 我测试了一下，没复现问题，配置这里应该是4行，你可以抓个包看看
> 
> ```
> ant=N&z0=&z1=oracle.jdbc.driver.OracleDriver%0Ajdbc%3Aoracle%3Athin%3A%40127.0.0.1%3A1521%2Ftest%0Auser%0Apassword
> ```
> 
> `%0A` 是换行符

![image](https://user-images.githubusercontent.com/16932404/57906911-3926d680-78ae-11e9-8e2b-7c52634275bc.png)
我也搞不明白，同样的环境，jsp文件放在同一个地方 只是String encoder = ""这里我是空的，另外一个正常的是base64。base64依然正常访问。
