### ISSUE TITLE
aspx shell +mssql 数据库无法导出

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#176]
如题
![image](https://user-images.githubusercontent.com/46088090/58026302-bd948600-7b48-11e9-8bf0-77a62db261db.png)

**Comment by Medicean** [comment]
see d7e31b04f8a89d0e56d0ab6213e3fb3bbacd2d61

**Comment by yzddmr6** [comment]
感谢，因为蚁剑检查更新的时候只能检测是否有2.3而不能检测2.2.1，我误以为自己是最新的版本，用git就好了
