### ISSUE TITLE
增删改表列的功能能否支持更多数据库

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#177]
如题
数据操作中能否增加右键添加表  删除表 增加列 删除列这种功能

**Comment by Medicean** [comment]
目前是支持的，具体看 v2.0.2 更新日志。
https://github.com/AntSwordProject/antSword/blob/master/CHANGELOG.md#20181205-v202

**Comment by yzddmr6** [comment]
感谢，能否在未来增加对更多数据库的支持呢

**Comment by Medicean** [comment]
这个实现起来过于复杂，我建议你直接上 navicat 的 agent

**Comment by yzddmr6** [comment]
ok
