### ISSUE TITLE
吐个槽！护网被黑名单坑惨了。

### ISSUE THREAD

**Issue by 5am3** [AntSwordProject/antSword#179]
如题....
护网被黑名单机制坑惨了，之前没发现。护网正儿八经日站时，发现目标站的shell都连不上....

**Comment by virink** [comment]
**哈哈哈哈（我们都是经过严格训练的,绝对不会笑,除非忍不住）
心疼你一秒**

**Comment by yzddmr6** [comment]
蚁剑是开源的,自己改啊.......................

**Comment by mumu0215** [comment]
源码目录下modules文件夹，修改config.js里限制黑名单的函数就行了

**Comment by loobug** [comment]
怎么修改？

**Comment by TajangSec** [comment]
> 源码目录下modules文件夹，修改config.js里限制黑名单的函数就行了

现在没有这个文件了，而且修改config里的没有用，貌似关键文件被打包成asar或者pak了

**Comment by ybm911** [comment]
> 源码目录下modules文件夹，修改config.js里限制黑名单的函数就行了

这个有用！！！
