### ISSUE TITLE
关于目录权限的问题

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#180]
![image](https://user-images.githubusercontent.com/46088090/58417475-77df3c80-80b7-11e9-80a2-490c0edd4553.png)
win的系统
整个站在蚁剑中显示都是777的目录权限
但实际上确实每个目录什么都写不进去

![image](https://user-images.githubusercontent.com/46088090/58417529-a2c99080-80b7-11e9-87c0-784b8c8f9a72.png)

**Comment by Medicean** [comment]
这么跟你说吧，这应该是 PHP 的问题。获取文件权限的时候，用的是 `fileperms` 这个函数。

在Windows NT / 2000 / XP / 2003中，PHP在确定文件属性时完全忽略 NTFS ACL 这个东西了，只取的是「文件属性」，所以出现你上面说的情况了。即使你用 `is_readable`,`is_writeable` 也是解决不了这个问题的。

解决问题的唯一方法是专门针对Win32使用Win32 API的`GetSecurityInfo()`调用进行更改。

参考： https://bugs.php.net/bug.php?id=26224

**Comment by yzddmr6** [comment]
OK
