### ISSUE TITLE
主目录错误的问题

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#181]
![image](https://user-images.githubusercontent.com/46088090/58418896-bb3baa00-80bb-11e9-821d-0531d58f1647.png)
打开shell后默认是一个不存在的路径
![image](https://user-images.githubusercontent.com/46088090/58418941-d60e1e80-80bb-11e9-92d3-69e4ca4cec76.png)
虚拟终端也无法使用
有waf  但是自己的编码器是过waf的,不知道是不是跟这个有关
这个图是default下截得
![image](https://user-images.githubusercontent.com/46088090/58418993-f50cb080-80bb-11e9-9c63-d33b601b96ef.png)

奇怪...还是第一次遇到这个问题...
对方php版本5.2

**Comment by Medicean** [comment]
给你提供2个解决的思路

1. 你先在测试环境里面测一下自己的「编码器」、「解码器」有没有问题
2. 挂上 burp，不要开拦截，然后看流量，手动把返回包解开看一下有没有问题

**Comment by yzddmr6** [comment]
我的编码器用了很久,从来没出过问题
我本地测了一下
返回数据包的前面应该是有当前shell的路径的
![image](https://user-images.githubusercontent.com/46088090/58420134-28047380-80bf-11e9-9bd7-e3471d1ccb7b.png)

但是他的返回数据包里没有
![image](https://user-images.githubusercontent.com/46088090/58420191-44081500-80bf-11e9-8a56-8cae3c98fc46.png)
所以导致了这个问题

**Comment by Medicean** [comment]
返回的主目录是 `.` ,可能是开了 `chroot` 也许你需要自己改一下 `base.js` 里面获取目录的代码，改完记得分享一下这块的东西，帮助我改进

https://github.com/AntSwordProject/antSword/blob/4afdb5649c910c6318d372ce0f58b60ec646a83f/source/core/php/template/base.js#L8

**Comment by yzddmr6** [comment]
好的

**Comment by yzddmr6** [comment]
又遇到这个问题了
对方环境还是php5.2
只不过这次是安全狗
![image](https://user-images.githubusercontent.com/46088090/59147469-91c13d80-8a2e-11e9-9148-14c01836d92e.png)

找了一下原因

发现
![image](https://user-images.githubusercontent.com/46088090/59147479-9c7bd280-8a2e-11e9-842c-2bcfdd20320b.png)

$_SERVER["SCRIPT_FILENAME"]变量是乱码
![image](https://user-images.githubusercontent.com/46088090/59147622-a0105900-8a30-11e9-8b42-a70474782596.png)
每次返回的乱码还不一样

开始以为是编码的问题
但是路径中并没有中文

用菜刀连接正常

抓了下包看了看


![image](https://user-images.githubusercontent.com/46088090/59147735-d7333a00-8a31-11e9-8f87-d61d19001623.png)

菜刀用的是dirname(\__FILE\__)
蚁剑用的是dirname($_SERVER["SCRIPT_FILENAME"]);
并且加了一句
if(PHP_VERSION<'5.3.0'){@set_magic_quotes_runtime(0);}
以为是set_magic_quotes_runtime的问题
但是还是不行

![image](https://user-images.githubusercontent.com/46088090/59147749-f6ca6280-8a31-11e9-93cf-e556a7efc165.png)


emmmmmm玄学问题
