### ISSUE TITLE
批量导入插件的改进建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#184]
当前的批量导入插件功能虽然实现了但是并不是很人性化
这是现在的使用说明
![image](https://user-images.githubusercontent.com/46088090/58710747-99119700-83ef-11e9-849b-4c073e009c51.png)

## 1
作为一个用户一般的习惯是先把url放到最前面,然后是密码.很多时候其实备注什么分类的并不要求

按照当前的样式,不管你想不想都必须在前面加上三个逗号(我不知道是不是因为菜刀的数据库格式是这样的作者才这样写)

理想中的格式:

`url,pass,*备注,*分类`

带*的为可以省略的选项

这样就不用每次在头部加 , 了

最简单的就

`url,pass`

简洁明了

## 2
其实应该支持自动识别后缀啊
一个个手工设置后缀的话很麻烦

## 3 
如果可以的话可以在头部加上各个类型shell的encoder的选项,能够自动加载当前的encoder并且默认采用选定的encoder保存

希望越做越好!

**Comment by yzddmr6** [comment]
并且导入后不支持最新的如`user-agent`等默认设置

**Comment by Medicean** [comment]
插件有关的，直接去对应的插件仓库下给作者提吧？

**Comment by yzddmr6** [comment]
OK
