### ISSUE TITLE
利用随机异或免杀D盾蚁剑版

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#186]
项目地址:
https://github.com/yzddmr6/as_php_xor_bypass

根据自己原来一个小项目改的,利用随机异或来免杀各种waf:
https://github.com/yzddmr6/php_xor_bypass

我记得蚁剑原来有一个生成的插件,但是生成的shell被D盾杀得妈都不认识了

刚好自己写过这个脚本,就想着自己改一下.

继承了原来的UI,现在把它集成到蚁剑的插件上了

使用截图:
![image](https://user-images.githubusercontent.com/46088090/58866339-fc9b0d80-86ea-11e9-8584-fcb87de6fb66.png)

过某盾截图

![image](https://user-images.githubusercontent.com/46088090/58866326-f3aa3c00-86ea-11e9-85ea-231b377d38ea.png)

此项目长期保持免杀更新,如果可以的话可以放进官方插件仓库

**Comment by virink** [comment]
Plz read [README.md](https://github.com/AntSword-Store/AntSword-Store.github.io) from AntSword-Store
![image](https://user-images.githubusercontent.com/15978207/58869604-1f302500-86f1-11e9-9acb-78e93b3514db.png)

**Comment by yzddmr6** [comment]
OK

**Comment by Medicean** [comment]
如果功能差不多的话，可以fork已经上架的 GenShell 插件，在基础上进行功能添加，再 PR 到那个plugin里

**Comment by yzddmr6** [comment]
是的  准备长期维护
已经发申请了
