### ISSUE TITLE
问题出在哪儿？... t.t (as_plugin_import_shell_from_csv

### ISSUE THREAD

**Issue by huitc** [AntSwordProject/antSword#193]
- [x] 我使用的操作系统是 ***Windows*** 10+
- [x] 我使用的是 64 位操作系统

```
,default,test,php,3241.testhaha.com/fxxkyou/index.php?123test123=eval($_POST['123test123']);
,default,test,php,1234.testhaha.com/fxxkyou/index.php?123test123=eval($_POST['123test123']);
```

添加成功但沒效果...... ^^''
### **成功**
```
成功 -> Count : 155
```

https://github.com/AntSword-Store/as_plugin_import_shell_from_csv
https://github.com/AntSwordProject/antSword
https://github.com/virink/as_plugin_import_shell_from_csv
@AntSwordProject
@AntSword-Store

**Comment by yzddmr6** [comment]
他这个插件不好用....一堆bug...

**Comment by Medicean** [comment]
1) url 的要求是必须以 `http://` 或者 `https://` 开头的, 你这个里面没有
2) 域名 / IP 需要能解析，因为在添加之后会根据URL解析出IP&&地理位置

**Comment by Medicean** [comment]
插件已经更新，更新状态如果看不到，可以明天再试，或者直接卸载重装

**Comment by huitc** [comment]
@Medicean 我根据「复制shell配置」写了php 但会设成自定義。。。
还有希望能多加encoder decoder multipart发包 忽略证书 可以跳转 等... pls.. thx...😅😅

**Comment by huitc** [comment]
因为对於数目大的真的不方便 所以。。。pls and thx!!😅😃

**Comment by huitc** [comment]
@Medicean @virink @AntSwordProject @AntSword-Store

**Comment by yzddmr6** [comment]
你说的这些我很早以前就给原作者提过了
https://github.com/virink/as_plugin_import_shell_from_csv/issues/1
你看看他的回复
自己写吧...
