### ISSUE TITLE
关于jsp一句话的建议

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#197]
当前的菜刀跟蚁剑的jsp型webshell都是通过custom模式来实现的

代码都放在shell中  使用的时候只需要post一个参数就可以了

但是带来的问题就是webshell实在太大了  

蚁剑的jspshell比菜刀的都长  有些时候对于有长度限制的getshell来说实在是不方便

冰蝎已经解决了这个问题   但是本人还是比较喜欢用蚁剑  所以希望蚁剑也能实现jsp一句话的功能

参考文章：https://xz.aliyun.com/t/2744

**Comment by yzddmr6** [comment]
另外  由于win的特性
cmd跟文件一个gbk一个utf8编码
然而当前的编码方式是在shell里面写死的只能选择一种
也就是说要么终端乱码要么文件内容乱码二选一
![image](https://user-images.githubusercontent.com/46088090/60762473-7ed47400-a093-11e9-8bf1-b6dde675db1d.png)

个人建议不要在shell里面写死  如果能用蚁剑客户端每次传一个编码参数能改变或者自动识别就更好了

冰蝎这一点做得比较好  大佬有空了可以研究一下

**Comment by zypperin** [comment]
我写过一个jsp的一句话，应该可以改造一下
https://github.com/zypperin/JSPBackdoor

**Comment by yzddmr6** [comment]
> 我写过一个jsp的一句话，应该可以改造一下
> https://github.com/zypperin/JSPBackdoor

妙哇
我是自己照着冰蝎改了一个传递字节码的[demo](https://yzddmr6.tk/posts/antsword-diy-3/)，但是蚁剑的后端是node所以就只能硬编码字节码。用你这种方法ScriptEngineManager调js就有eval了，厉害厉害。

**Comment by yzddmr6** [comment]
已实现
https://yzddmr6.tk/posts/antsword-diy-3/
