### ISSUE TITLE
新功能建议：增加标签的显示方式设置

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/antSword#206]
表哥还是老问题。。。

![image](https://user-images.githubusercontent.com/46088090/63221828-297e9d00-c1d1-11e9-8acb-bbd1ab014fa8.png)

就是有些人喜欢标签上是域名，有些人喜欢标签上是ip

希望在设置中能增加一个选项控制显示方式

感谢

**Comment by ylqingf** [comment]
+1
我也觉得这样比较好

**Comment by yzddmr6** [comment]
懒得改了 算了
