### ISSUE TITLE
自定义分割符号

### ISSUE THREAD

**Issue by supermisscat** [AntSwordProject/antSword#208]
目前遇到有些WAF会直接拦截首次访问的->||<-，包括部分流量设备会以这个为特征正则抓取内容，是否可以做成可配置分隔符的模式？虽然可以自行修改代码，但是下次更新代码被覆盖又要重新改了。

**Comment by Medicean** [comment]
除了 CUSTOM 类型的，其它类型的数据分割符已经是随机产生的了

**Comment by supermisscat** [comment]
> 随机

嗯。就是custom。:(

**Comment by ViCrack** [comment]
custom就不太好弄成通用随机了，毕竟这部分代码在服务端是写死的

**Comment by supermisscat** [comment]
好吧
