### ISSUE TITLE
客户端-AES加密中文乱码

### ISSUE THREAD

**Issue by supermisscat** [AntSwordProject/antSword#214]
测试AES加密，用的hex编码方式，解码器是返回正常中文了，但是在客户端上却还是显示乱码，是否需要改哪里的配置？在添加数据的地方改过编码了不行。
调试的输出：
![image](https://user-images.githubusercontent.com/16932404/64483831-1133f800-d23c-11e9-93ab-069c00bf597b.png)

**Comment by Medicean** [comment]
@supermisscat 建议你在服务端先 base64 之后，再使用 aes

JSP 的参考这个脚本
https://github.com/AntSwordProject/AwesomeScript/blob/master/jsp/jsp_custom_script_for_mysql.jsp

**Comment by supermisscat** [comment]
> @supermisscat 建议你在服务端先 base64 之后，再使用 aes
> 
> JSP 的参考这个脚本
> https://github.com/AntSwordProject/AwesomeScript/blob/master/jsp/jsp_custom_script_for_mysql.jsp

好的，只是我不明白为啥返回已经是中文了界面上还是乱码而已。thx
