### ISSUE TITLE
SuperTerm之CORS问题

### ISSUE THREAD

**Issue by vungsung** [AntSwordProject/antSword#217]
![image](https://user-images.githubusercontent.com/32069685/65324758-b60ce880-dbdf-11e9-8539-f594c04fdfd0.png)
被Chromium的CORS挡下来了... SuperTerm完全无法使用 ,感谢协助!

**Comment by Medicean** [comment]
我记得是更新过了，你看一下你的 superterm 插件是不是 0.2 版本

 https://github.com/AntSword-Store/SuperTerm/commit/dbdfaab70a18c19ad696fd0a4baa3813e1c6db04

**Comment by vungsung** [comment]
![image](https://user-images.githubusercontent.com/32069685/65389179-b6df7f00-dd85-11e9-86ce-2ead47136c48.png)

**Comment by vungsung** [comment]
再次clone并覆盖了整个SuperTerm repo，确认Windows 10 x64上有问题

**Comment by Medicean** [comment]
@vungsung windows 下的client文件名搞错了，已经修正了，感谢
