### ISSUE TITLE
蚁剑连接某些国外的报错，IP is not in the cert's list

### ISSUE THREAD

**Issue by 627510582** [AntSwordProject/antSword#221]
![image](https://user-images.githubusercontent.com/22499439/66640125-e7129300-ec4a-11e9-8977-8a93d7ed3ca2.png)

**Comment by Medicean** [comment]
「编辑数据」-> 「其它设置」 勾上「忽略HTTPS证书」

**Comment by 627510582** [comment]
解决了 谢谢
