### ISSUE TITLE
无法使用，无界面

### ISSUE THREAD

**Issue by cnsimo** [AntSwordProject/antSword#223]
初始化目录后，打开这样的，没有界面
![image](https://user-images.githubusercontent.com/22788893/68137310-b7149200-ff61-11e9-8e0a-21067f9657bf.png)

**Comment by cnsimo** [comment]
windows 10，loader4.0.3，最新antsword

**Comment by Medicean** [comment]
已经确认，无问题，请从自身找原因。

建议：

1. 查看源代码所在目录是否有写权限
2. 重新 clone 源代码
3.  打开调试控制台代码注释 https://github.com/AntSwordProject/antSword/blob/master/app.js#L91
