### ISSUE TITLE
源码下载不下来， 下到百分之70多就链接失败了。试了一晚上了

### ISSUE THREAD

**Issue by Xuzan9396** [AntSwordProject/antSword#225]

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/69018625-34231b00-09e8-11ea-83cf-55e8095c149f.png)
![image](https://user-images.githubusercontent.com/24741439/69018636-4309cd80-09e8-11ea-9ab1-11cd3df7194d.png)

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/69019066-ef987f00-09e9-11ea-8c4e-58eabf43e3cc.png)

**Comment by Medicean** [comment]
网络问题，自己挂代理处理

**Comment by Xuzan9396** [comment]
@Medicean 下载源码了， 怎么运行？ 说明说上只有加载器

**Comment by Xuzan9396** [comment]
@Medicean  加载器一直初始化失败

**Comment by Xuzan9396** [comment]
@Medicean  大佬可以了， 我挂了全局代理，解决了，3q
