### ISSUE TITLE
客户端-AES加密中文乱码（服务端base64-aes-base64）

### ISSUE THREAD

**Issue by RoyTse** [AntSwordProject/antSword#227]
- [x ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ x] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [ x] 我使用的是 64 位操作系统

### Bug 详细描述

测试AES的时候，console.log已经实现中文，但是在终端里面显示为乱码。
![P7HI_3LQ7I_E1UE0NM3@0GG](https://user-images.githubusercontent.com/23696367/69030679-423a6100-0a13-11ea-8c8c-7af8bc2c7a0a.png)
同时，我使用示例的AES加密编码器加密中文，然后把加密后的密文解密。console.log显示中文。但是在终端也显示乱码。所以我觉得应该是客户端的编码BUG

**Comment by Medicean** [comment]
把用到的相关的「编码器」、「Shell脚本」、「antSword」和 GitHub 上比对一下

**Comment by RoyTse** [comment]
![BCJ521S$_S72P@)70SM{93](https://user-images.githubusercontent.com/23696367/69041253-28584880-0a2a-11ea-8d77-45581c6369b0.png)
这是我的antsword版本。从github下载的。
这是我今天下载的PHP示例下的编码器。
不使用shell脚本也能返回结果。因为我把decode_buff修改了一下。加密指定字符串，返回指定字符串给结果输出到终端。


`/**
 * php::aes-256-cfb (zeroPadding) 解码器
 * Create at: 2019/05/12 15:43:55
 */

'use strict';
const path = require('path');
var CryptoJS = require(path.join(window.antSword.remote.process.env.AS_WORKDIR, 'node_modules/crypto-js'));

function get_cookie(Name, CookieStr="") {
   var search = Name + "="
   var returnvalue = "";
   if (CookieStr.length > 0) {
     var sd = CookieStr.indexOf(search);
     if (sd!= -1) {
        sd += search.length;
        var end = CookieStr.indexOf(";", sd);
        if (end == -1){
          end = CookieStr.length;
        }
        returnvalue = window.unescape(CookieStr.substring(sd, end));
      }
   } 
   return returnvalue;
}

function decryptText(keyStr, text) {
  let buff = Buffer.alloc(32, 'a');
  buff.write(keyStr,0);
  keyStr = buff.toString();
  let decodetext = CryptoJS.AES.decrypt(text, CryptoJS.enc.Utf8.parse(keyStr), {
    iv: CryptoJS.enc.Utf8.parse(keyStr),
    mode: CryptoJS.mode.CFB,
    padding: CryptoJS.pad.ZeroPadding
  }).toString(CryptoJS.enc.Utf8);
  return decodetext;
}

function encryptText(keyStr, text) {
  let buff = Buffer.alloc(32, 'a');
  buff.write(keyStr,0);
  keyStr = buff.toString();
  let encodetext = CryptoJS.AES.encrypt(text, CryptoJS.enc.Utf8.parse(keyStr), {
    iv: CryptoJS.enc.Utf8.parse(keyStr),
    mode: CryptoJS.mode.CFB,
    padding: CryptoJS.pad.ZeroPadding,
  }).toString();
  return encodetext;
}

module.exports = {
  /**
   * @returns {string} asenc 将返回数据base64编码
   * 自定义输出函数名称必须为 asenc
   * 该函数使用的语法需要和shell保持一致
   */
  asoutput: () => {
    return `function asenc($out){
      $key=substr(str_pad(session_id(),32,'a'),0,32);
      $iv=$key;
      return @base64_encode(openssl_encrypt(base64_encode($out), "AES-256-CFB", $key,OPENSSL_RAW_DATA|OPENSSL_ZERO_PADDING, $iv));
    }
    `.replace(/\n\s+/g, '');
  },
  /**
   * 解码字符串
   * @param {string} data 要被解码的字符串
   * @returns {string} 解码后的字符串
   */
  decode_str: (data, ext={}) => {
    if(data.length === 0) {
      return data;
    }
    let headers = ext.opts.httpConf.headers;
    if(!headers.hasOwnProperty('Cookie')) {
      window.toastr.error("请先设置 Cookie (大小写敏感), 可通过浏览网站获取Cookie", "错误");
      return data;
    }
    let session_key = "PHPSESSID";
    let keyStr = get_cookie(session_key, headers['Cookie']);
    if(keyStr.length === 0) {
      window.toastr.error("未在 Cookie 中发现PHPSESSID", "错误");
      return data;
    }
    let ret = decryptText(keyStr, data);
    return Buffer.from(ret, 'base64').toString();
  },
  /**
   * 解码 Buffer
   * @param {string} data 要被解码的 Buffer
   * @returns {string} 解码后的 Buffer
   */
  decode_buff: (data, ext={}) => {
    if(data.length === 0) {
      return data;
    }
    let headers = ext.opts.httpConf.headers;
    if(!headers.hasOwnProperty('Cookie')) {
      window.toastr.error("请先设置 Cookie (大小写敏感), 可通过浏览网站获取Cookie", "错误");
      return data;
    }
    let session_key = "PHPSESSID";
    let keyStr = get_cookie(session_key, headers['Cookie']);
    if(keyStr.length === 0) {
      window.toastr.error("未在 Cookie 中发现PHPSESSID", "错误");
      return data;
    }
	let en = encryptText("1234567887654321","你好啊aaaaa");
  let de = decryptText("1234567887654321",en);
  console.log(de);
  return de;
    //return Buffer.from(decryptText(keyStr, Buffer.from(data).toString()), 'base64');
  }
}`

**Comment by RoyTse** [comment]
![9{S0`J4IHCWRYQLGHR_`Y3G](https://user-images.githubusercontent.com/23696367/69042317-f47e2280-0a2b-11ea-87c3-b7c8fd7fa822.png)
这是我的测试结果。如果一切正常的话，输入任意命令应该返回你好啊aaaaa在终端。

我刚刚检查更新并升级到2.17了。还是同样的错误。我在两台windows电脑上分别测试。均有相同问题。请问你是否能复现该问题。

![NO}E)请问你是否能复现该问题。

VL}E~Y25@Y8%Z%32](https://user-images.githubusercontent.com/23696367/69042636-8423d100-0a2c-11ea-85ea-d162ed3d05eb.png)

**Comment by Medicean** [comment]
`decryptText` 返回的是 `String`, 而 `decode_buff` 需要返回 `Buffer`, String 和 Buffer 不是一个东西

说了半天都没明白你说的在哪。你使用的到底是 aspx, php 还是 custom 的 aspx 脚本，你这个得确定一下。

**Comment by RoyTse** [comment]
不好意思，我把事情梳理一下。我是想编写一个ashx-custom的aes加密模板（解码器使用的php-aes模板修改的，webshell使用aspx模板修改的）。

写好后发现中文乱码。然后我在decoder里面自定义加密"你好啊aaaaa"，然后将加密后的结果解密。最后把解密的结果替换掉shell返回的解密结果（试图排除是服务端返回数据出现问题），发现终端也是一样的乱码。

最后我将解密后的结果通过console.log输出。在调试日志中数据不是乱码。所以我认为是antsword终端显示出了问题。

以上就是我遇到的问题。

简单来说就是我使用php-aes编码器、解码器模板自带的函数对中文进行加解密后。解密的数据在控制台为正确的中文，但是返回给终端就会导致乱码。

**Comment by RoyTse** [comment]
感谢你的解答，问题出在我返回的是String，而不是Buffer！
当我改成返回Buffer后就没有问题了

**Comment by Medicean** [comment]
直接用这个:

https://github.com/AntSwordProject/AwesomeEncoder/blob/master/custom/decoder/aes_128_cfb_zeropadding_base64.js
