### ISSUE TITLE
大佬们，php 根目录下放了这个脚本，链接菜刀，我的ip立马就被阿里云封了，有啥办法嘛

### ISSUE THREAD

**Issue by Xuzan9396** [AntSwordProject/antSword#228]
- [ ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [ ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [x] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

---

## 新功能建议

- [ ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [x] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

---

### shell 连接 Bug

1. 服务端操作系统

2. 服务端shell代码

3. 服务端环境配置

4. 客户端连接配置

**Comment by Medicean** [comment]
自己先找文章学习完再来问吧。

**Comment by virink** [comment]
Bypass 阿里云的 WAF 啊。
你得先听我说！你不是这样子的！
你得先这样，然后再这样，接着再这样，最后你再这样！听懂没有？
我都说了，不是！不是这样子的！你先好好听我说！认真地听我说！你得先这样！然后你再这样！接着再这样！最后你再这样！你听明白了吗？
啊哟喂！你可真是怪了！我说得这么清楚，你怎么就听不明白呢？什么！你居然听不懂！天啊！你这是要气死我，是不是？好好！我再详细地和你说清楚！
你得先这样，然后再这样，接着再这样，最后你再这样！是不是？很简单的！先这样，再这样，接着这样，最后再这样！
**对对！对对！它就是这样的！你总算是听明白了！就是这样！**

**Comment by Xuzan9396** [comment]
@Medicean  没学习还问不了？
