### ISSUE TITLE
当web是一个挂载的网络路径的时候有问题

### ISSUE THREAD

**Issue by nullnull1604-outlook** [AntSwordProject/antSword#229]
web是一个网络路径的时候，也就是说，shell放在一个相对于web服务器的网络文件夹中，报错

![image](https://user-images.githubusercontent.com/58207759/69705782-33e5f680-1131-11ea-8ba9-2119fbdaf3aa.png)

**Comment by Medicean** [comment]
可否提供一下具体的环境搭建步骤和复现步骤

**Comment by nullnull1604-outlook** [comment]
额，你可以搭建一个smb服务器共享一个文件夹，然后让web服务器使用这个网络文件夹作为web根目录，然后写一句话webshell，连接，然后就是这个错误。。。。。使用菜刀连接没有问题

**Comment by nullnull1604-outlook** [comment]
就是smb建立一个共享目录，everyone的那种，然后web指定根目录的时候指定一个网络目录

**Comment by Medicean** [comment]
已成功复现，非常感谢反馈。
初步判断是因为 UNC Path 开头是 `\` 识别成了 Linux系统，所以调用不成功。决定增加一个手动切换的指令，可以在自动识别操作系统错误的时候手动切换。

**Comment by Medicean** [comment]
* 新增 `aswinmode` 本地指令, 在自动识别操作系统错误时, 可使用该指令手动切换命令行运行的模式 (#229 thx @nullnull1604-outlook)

![terminal_aswinmode.png](https://i.loli.net/2019/12/03/HpbjN6sERhYoiUX.png)

**Comment by nullnull1604-outlook** [comment]
作者你好，连接上webshell后，使用net use挂载一个网络的共享后，一般情况下，在文件管理的界面输入路径就可以跳过去的，但是像是这种webshell在一个网络路径的情况下，好像就不行

**Comment by Medicean** [comment]
@nullnull1604-outlook  也是可以进去的，我上面发的截图就是 shell 在 smb 里。

**Comment by nullnull1604-outlook** [comment]
.......额，我没试匿名的，如果smb设置有账号密码，然后我再虚拟终端中使用net use挂载，在webshell不在网络路径的情况下，可以使用文件管理直接访问到，但是在webshell在网络路径的情况下就不行，net use挂载成功后，copy路径到文件管理，输入路径，访问，显示路径错误，地址栏会默认加上一段webshell的那个网络路径

**Comment by Medicean** [comment]
@nullnull1604-outlook 用 net use 挂载之后，是会有盘符的，清掉缓存之后，再重新进文件管理，就能看到新的盘符了。
