### ISSUE TITLE
能否增加源码打包的功能呢

### ISSUE THREAD

**Issue by 9tail123** [AntSwordProject/antSword#235]
能否增加源码打包的功能呢，虽然linux下有类似命令，但windows上不是所有都有winrar

**Comment by ca3tie1** [comment]
> 能否增加源码打包的功能呢，虽然linux下有类似命令，但windows上不是所有都有winrar

没有winrar的时候可以把自己电脑上winrar安装目录下的Rar.exe上传到服务器 执行打包 我一般都是如此操作的，只需上传Rar.exe即可

**Comment by virink** [comment]
该功能不予考虑

**Comment by 9tail123** [comment]
好的 多谢
