### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by kelis-cpu** [AntSwordProject/antSword#243]
- [x] 我确定这是蚁剑本身的一个 Bug，我并是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug
- [ ] 我使用的操作系统是 ***Windows*** 10+
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

![70068887-ce5fa180-162b-11ea-94cc-9dda3c75c37d](https://user-images.githubusercontent.com/59810499/72250462-98eca180-3636-11ea-80d3-4432c34dbb97.jpg)

---

**Comment by IcecreamArtist** [comment]
我也遇到了这个问题、、

**Comment by adhere534** [comment]
一样

**Comment by keerge** [comment]
可能是宝塔某些特性导致，尝试在header加上 Connection：keep-alive

**Comment by Medicean** [comment]
`ECONNRESET` 全称 `Error Connect Reset` 连接被重置，自行检查 WAF
