### ISSUE TITLE
问个问题，为什么插件安装后，右键看不到，无法使用？

### ISSUE THREAD

**Issue by IMnewer** [AntSwordProject/antSword#250]
RT，谢谢

**Comment by Medicean** [comment]
原因是出在 JWT Debugger 这个插件上，从 github 下载的 zip 包中解压的时候 package.json 这个文件丢失了。

1. 进入 antData/plugins/as_jwtdebugger-master/ 这个目录

2. 新建 package.json 文件，内容见链接:

https://github.com/AntSword-Store/as_jwtdebugger/blob/master/package.json

3. 重启 antSword
