### ISSUE TITLE
加载器安装出错

### ISSUE THREAD

**Issue by 496672097** [AntSwordProject/antSword#251]
- [x ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [ ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题

- [ x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [x ] 我使用的操作系统是 ***Windows*** 10+

- [ x ] 我使用的是 64 位操作系统

**Comment by Medicean** [comment]
网络问题，导致压缩包下载缺失。尝试手动下载源码包解决。

**Comment by 5z1punch** [comment]
遇到同样问题，手动下载也出现同样问题，系统环境相同，提示解压失败，手动可以正常解压

**Comment by s1awwhy** [comment]
同样遇到问题。源码包解压提示数据损坏

**Comment by Yexi-lin** [comment]
如果不是下载丢包（md5核实无误），尝试用管理员权限手动解压

**Comment by acommonname** [comment]
md5核实无误后用管理员权限运行AntSword.exe即可

**Comment by acommonname** [comment]
md5核实无误后用管理员权限运行AntSword.exe即可
