### ISSUE TITLE
插件中心远程仓库加载不出来

### ISSUE THREAD

**Issue by al4n233** [AntSwordProject/antSword#254]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ x] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [ x] 我使用的是 64 位操作系统

### Bug 详细描述

---

## 新功能建议

- [ ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [ ] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

---

### shell 连接 Bug

1. 服务端操作系统

2. 服务端shell代码

3. 服务端环境配置

4. 客户端连接配置

尝试过重启，挂香港，俄罗斯代理都还是加载不出来插件中心远程仓库

**Comment by dd2008** [comment]
我的也是加载不出来

**Comment by strawerlar** [comment]
一直转圈

**Comment by Medicean** [comment]
把你挂代理的截图亮出来

**Comment by strawerlar** [comment]
> 把你挂代理的截图亮出来

我这没有用代理，访问github正常，需要走代理么？

**Comment by Medicean** [comment]
一般来说不需要，加载不出来的情况就是某个请求没成功，所以最好是挂上稳定的socks5代理

**Comment by strawerlar** [comment]
找到解决方法了，应该是部分GITHUB的域名解析失败了，在网上找ip 添加HOST解决了 @al4n233 @dd2008

**Comment by xiaowaliu** [comment]
![image](https://user-images.githubusercontent.com/69131738/104797498-75d07100-57f9-11eb-904f-4df48e7cc944.png)
插件市场一直在转圈，不知道什么原因，加载不出来，求解决方法，没有使用代理，win10系统

**Comment by hausa-han** [comment]
> 找到解决方法了，应该是部分GITHUB的域名解析失败了，在网上找ip 添加HOST解决了 @al4n233 @dd2008

师傅可以发一下HOST吗0.0，谢谢您【/鼓掌】

**Comment by fe1w0** [comment]
我的问题是商店中心界面一直在加载,环境一样

![image](https://user-images.githubusercontent.com/50180586/109022859-33069080-76f7-11eb-840a-4ab382d660e0.png)

**Comment by saucer-man** [comment]
![image](https://user-images.githubusercontent.com/32133080/109420791-365b8e00-7a0f-11eb-9525-af5a63faf429.png)

dns有毒，我手动把dns写到hosts文件就好了

```
echo 185.199.111.133 raw.githubusercontent.com | sudo tee -a /etc/hosts
```

**Comment by Medicean** [comment]
#277

**Comment by CTFWeb** [comment]
<img width="691" alt="image" src="https://github.com/AntSwordProject/antSword/assets/135563954/013b65f6-a469-4b6a-992f-ada891920cd2">

**Comment by xiaohuangHKX** [comment]
![image](https://github.com/user-attachments/assets/ae228ffa-f686-4b85-b7a6-1b92a7cd540b)
这种怎么处理呀

**Comment by CTFWeb** [comment]
自动回复邮件。automatically reply e-mail你好，你的邮件我已收到，将会尽快给你回复。Hello, I have received your email and will reply to you as soon as possible.

**Comment by Theory-of-God** [comment]
> 我的问题是商店中心界面一直在加载,环境一样
> 
> ![image](https://user-images.githubusercontent.com/50180586/109022859-33069080-76f7-11eb-840a-4ab382d660e0.png)
在代理里面选手动代理，ip为本机，端口为你梯子的端口，协议选SOCKS5测试成功应该就行了。

**Comment by CTFWeb** [comment]
自动回复邮件。automatically reply e-mail你好，你的邮件我已收到，将会尽快给你回复。Hello, I have received your email and will reply to you as soon as possible.

**Comment by Theory-of-God** [comment]
> ![image](https://private-user-images.githubusercontent.com/153483373/350266789-ae228ffa-f686-4b85-b7a6-1b92a7cd540b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDA2MTQsIm5iZiI6MTcyNjA0MDMxNCwicGF0aCI6Ii8xNTM0ODMzNzMvMzUwMjY2Nzg5LWFlMjI4ZmZhLWY2ODYtNGI4NS1iN2E2LTFiOTJhN2NkNTQwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwNzM4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmY2NWVhMDU1NjQxOGQwZmY3M2JmNzVjZTdiZjdhYTFiMzczNTMzNGUwODhiZTU1NGQ5MzVlYzQ4ZDYxMTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g2eSqJH6E7hh1h9iPD5ksXqcgMC-B432FZjxsalcBqI) 这种怎么处理呀

在代理里面选手动代理，ip为本机，端口为你梯子的端口，协议选SOCKS5测试成功应该就行了。
