### ISSUE TITLE
终端执行系统命令时，存在Bug 

### ISSUE THREAD

**Issue by An0ny-m0us** [AntSwordProject/antSword#267]
请问，这种情况是不是/bin/bash字段在传递的时候存在问题？
![1](https://user-images.githubusercontent.com/41460798/100860133-12011b80-34cb-11eb-9a6a-ed29d0f395e5.jpg)
![2](https://user-images.githubusercontent.com/41460798/100860145-175e6600-34cb-11eb-9212-4c3c8575fc7b.jpg)

**Comment by Medicean** [comment]
你使用的 WebShell 未完全实现 antSword Custom 类型的接口，参考 https://github.com/AntSwordProject/AwesomeScript/blob/master/jsp/jsp_custom_script_for_mysql.jsp
