### ISSUE TITLE
连接postgresql失败

### ISSUE THREAD

**Issue by helinze** [AntSwordProject/antSword#271]
- [x ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [x ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [ x] 我使用的是 64 位操作系统

### Bug 详细描述

---

## 新功能建议

- [ ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [ ] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

---

### shell 连接 Bug

1. 服务端操作系统

2. 服务端shell代码

3. 服务端环境配置

4. 客户端连接配置

**Comment by helinze** [comment]
这是我改的php postgresql 代码，请审查：
/**
 * 数据库管理模板::postgresql
 * i 数据分隔符号 => \t|\t
 */

module.exports = (arg1, arg2, arg3, arg4, arg5, arg6) => ({
  // 显示所有数据库
  show_databases: {
    _: `$m=get_magic_quotes_gpc();
      $hst=$m?stripslashes($_POST["${arg1}"]):$_POST["${arg1}"];
      $usr=$m?stripslashes($_POST["${arg2}"]):$_POST["${arg2}"];
      $pwd=$m?stripslashes($_POST["${arg3}"]):$_POST["${arg3}"];
      $arr=array(
        'host'=>explode(':',$hst)[0],
        'port'=>explode(':',$hst)[1],
        'dbname'=>explode(':',$hst)[2],
        'user'=>$usr,
        'password'=>$pwd,
      );
      $cs='';
      foreach($arr as $k=>$v) {
        if(empty($v)){
            continue;
        }
        $cs .= "$k=$v ";
     }
      $T=@pg_connect($cs);
      if(!$T){
        echo("ERROR://".@pg_last_error());
      }else{
        $q=@pg_query($T,"SELECT datname FROM pg_database where datistemplate='f';");
        if(!$q){
          echo("ERROR://".@pg_last_error());
        }else{
          while($rs=@pg_fetch_row($q)){
            echo(trim($rs[0]).chr(9));
          }
          @pg_free_result($q);
        }
        @pg_close($T);
      }`.replace(/\n\s+/g, ''),
    [arg1]: '#{host}',
    [arg2]: '#{user}',
    [arg3]: '#{passwd}',
    [arg4]: '#{db}'
  },
  // 显示数据库所有表
  show_tables: {
    _: `$m=get_magic_quotes_gpc();
      $hst=$m?stripslashes($_POST["${arg1}"]):$_POST["${arg1}"];
      $usr=$m?stripslashes($_POST["${arg2}"]):$_POST["${arg2}"];
      $pwd=$m?stripslashes($_POST["${arg3}"]):$_POST["${arg3}"];
      $dbn=$m?stripslashes($_POST["${arg4}"]):$_POST["${arg4}"];
      $arr=array(
        'host'=>explode(':',$hst)[0],
        'port'=>explode(':',$hst)[1],
        'dbname'=>$dbn,
        'user'=>$usr,
        'password'=>$pwd,
      );
      $cs='';
      foreach($arr as $k=>$v) {
        if(empty($v)){
            continue;
        }
        $cs .= "$k=$v ";
     }
      $T=@pg_connect($cs);
      if(!$T){
        echo("ERROR://".@pg_last_error());
      }else{
        $q=@pg_query($T,"SELECT table_name FROM information_schema.tables WHERE table_schema NOT IN ('pg_catalog', 'information_schema');");
        if(!q){
          echo("ERROR://".@pg_last_error());
        }else{
          while($rs=@pg_fetch_row($q)){
            echo(trim($rs[0]).chr(9));
          }
          @pg_free_result($q);
        }
        @pg_close($T);
      }`.replace(/\n\s+/g, ''),
    [arg1]: '#{host}',
    [arg2]: '#{user}',
    [arg3]: '#{passwd}',
    [arg4]: '#{db}',
  },
  // 显示表字段
  show_columns: {
    _: `$m=get_magic_quotes_gpc();
      $hst=$m?stripslashes($_POST["${arg1}"]):$_POST["${arg1}"];
      $usr=$m?stripslashes($_POST["${arg2}"]):$_POST["${arg2}"];
      $pwd=$m?stripslashes($_POST["${arg3}"]):$_POST["${arg3}"];
      $dbn=$m?stripslashes($_POST["${arg4}"]):$_POST["${arg4}"];
      $tab=$m?stripslashes($_POST["${arg5}"]):$_POST["${arg5}"];
      $arr=array(
        'host'=>explode(':',$hst)[0],
        'port'=>explode(':',$hst)[1],
        'dbname'=>$dbn,
        'user'=>$usr,
        'password'=>$pwd,
      );
      $cs='';
      foreach($arr as $k=>$v) {
        if(empty($v)){
            continue;
        }
        $cs .= "$k=$v ";
     }
      $T=@pg_connect($cs);
      if(!$T){
        echo("ERROR://".@pg_last_error());
      }else{
        $q=@pg_query($T,"SELECT column_name,udt_name,character_maximum_length FROM information_schema. COLUMNS WHERE TABLE_NAME = '{$tab}';");
        if(!$q){
          echo("ERROR://".@pg_last_error());
        }else{
          while($rs=@pg_fetch_row($q)){
            $len=$rs[2]?$rs[2]:"0";
            echo(trim($rs[0])." ({$rs[1]}({$len}))".chr(9));
          }
          @pg_free_result($q);
        }
        @pg_close($T);
      }`.replace(/\n\s+/g, ''),
    [arg1]: '#{host}',
    [arg2]: '#{user}',
    [arg3]: '#{passwd}',
    [arg4]: '#{db}',
    [arg5]: '#{table}',
  },
  // 执行SQL语句
  query: {
    _: `$m=get_magic_quotes_gpc();
      $hst=$m?stripslashes($_POST["${arg1}"]):$_POST["${arg1}"];
      $usr=$m?stripslashes($_POST["${arg2}"]):$_POST["${arg2}"];
      $pwd=$m?stripslashes($_POST["${arg3}"]):$_POST["${arg3}"];
      $dbn=$m?stripslashes($_POST["${arg4}"]):$_POST["${arg4}"];
      $sql=base64_decode($_POST["${arg5}"]);
      $encode=$m?stripslashes($_POST["${arg6}"]):$_POST["${arg6}"];
      $arr=array(
        'host'=>explode(':',$hst)[0],
        'port'=>explode(':',$hst)[1],
        'dbname'=>$dbn,
        'user'=>$usr,
        'password'=>$pwd,
      );
      $cs='';
      foreach($arr as $k=>$v) {
        if(empty($v)){
            continue;
        }
        $cs .= "$k=$v ";
      }
      $T=@pg_connect($cs);
      if(!$T){
        echo("ERROR://".@pg_last_error());
      }else{
        $q=@pg_query($T, $sql);
        if(!$q){
          echo("ERROR://".@pg_last_error());
        }else{
          $n=@pg_num_fields($q);
          if($n===NULL){
            echo("Status\t|\t\r\n");
            echo(base64_encode("ERROR://".@pg_last_error())."\t|\t\r\n");
          }elseif($n===0){
            echo("Affect Rows\t|\t\r\n".base64_encode(@pg_affected_rows($q))."\t|\t\r\n");
          }else{
            for($i=0;$i<$n;$i++){
              echo(@pg_field_name($q,$i)."\t|\t");
            }
            echo "\r\n";
            while($row=@pg_fetch_row($q)){
              for($i=0;$i<$n;$i++){
                echo(base64_encode($row[$i]!==NULL?$row[$i]:"NULL")."\t|\t");
              }
              echo "\r\n";
            }
          }
          @pg_free_result($q);
        }
        @pg_close($T);
      }`.replace(/\n\s+/g, ''),
    [arg1]: '#{host}',
    [arg2]: '#{user}',
    [arg3]: '#{passwd}',
    [arg4]: '#{db}',
    [arg5]: '#{base64::sql}',
    [arg6]: '#{encode}'
  }
})

**Comment by Medicean** [comment]
谢谢反馈。postgresql 在连接的时候是需要指定 dbname 的，之前漏掉了。

**Comment by helinze** [comment]
在您还没处理之前，我先修改一下用着，就在host上在用ip:port:dbname的方式强加一个在里面，改改代码，先急用
