### ISSUE TITLE
插件市场加载不出，你们是怎么解决的？

### ISSUE THREAD

**Issue by hackercreator** [AntSwordProject/antSword#277]
自带的代理功能我填了自建的socks5代理服务器的信息，无法正常代理，后来我用proxychains打开蚁剑就能加载出了，可是最近proxychains无法打开蚁剑了，打开是一片空白，连个操作选项都没有，不用proxychains就正常了，所以我想问问你们是怎么访问插件市场的，反正正常情况没有代理我是怎么都加载不出

**Comment by Medicean** [comment]
执行这两条命令看一下

```
$ ping api.github.com
$ ping raw.githubusercontent.com
```

**Comment by hackercreator** [comment]
> 
> 
> 执行这两条命令看一下
> 
> ```
> $ ping api.github.com
> $ ping raw.githubusercontent.com
> ```
> 
> 参考一下： https://mp.weixin.qq.com/s/hF3GgZpIcussc-BjUoJUuQ

好的谢谢

**Comment by Polestar666** [comment]
https://cloud.tencent.com/developer/article/1904883
请参考这个连接!!

**Comment by talentno** [comment]
我也是挂了梯子还是打不开，怎么解决啊？
