### ISSUE TITLE
## 报告 Bug

### ISSUE THREAD

**Issue by TryA9ain** [AntSwordProject/antSword#280]
- [ ] 我使用的操作系统是 ***macOSBigSur11.2.3*** 更新至AntSword v2.1.11.1 之后点关闭只关闭页面，进程并不能退出，只能强制退出进程

**Comment by TryA9ain** [comment]
> 按Cmd + Q退出
> 
> 参考：[https](https://github.com/AntSwordProject/antSword/blob/master/CHANGELOG.md#%E5%85%B6%E5%AE%83) : [//github.com/AntSwordProject/antSword/blob/master/CHANGELOG.md#%E5%85%B6%E5%AE%83](https://github.com/AntSwordProject/antSword/blob/master/CHANGELOG.md#%E5%85%B6%E5%AE%83)
> 
> * 单击窗口的关闭按钮，最小化至系统托盘。
> * 点击托盘菜单中的“退出”程序退出。
> * 点击菜单中的“退出程序”程序退出。

收到，个人问题，已解决谢谢

**Comment by zerokeeper** [comment]
- 点击托盘菜单中的「退出」程序退出
程序并不能退出，mac high sierra，2.1.14版本，这个可以解决一下吗。
另外还是比较喜欢单击窗口的关闭按钮，程序退出，更方便点
