### ISSUE TITLE
建议编解码器增加更多的传入参数和操作方法

### ISSUE THREAD

**Issue by burpheart** [AntSwordProject/antSword#282]
## 新功能建议
建议编解码器增加更多的传入参数
### 新功能描述

在编解码器传入参数增加webshellurl (实现传回数据隐藏在header的功能)(为了实现像冰蝎一样的动态秘钥交换和其他特殊功能 比如某些特殊shell的初始化操作 在编码器中直接与webshell进行通信)

在编码器增加临时header修改(实现传入数据隐藏在header的功能 包括请求方法修改 比如 GET PUT HEAD)

在解码器传入参数增加完整header (实现传回数据隐藏在header的功能)

**Comment by Medicean** [comment]
编码器的 ext 参数，参考：

https://github.com/AntSwordProject/AwesomeEncoder/blob/master/php/encoder/aes_256_cfb_zero_padding.js

另外，注意增加了header之后及时清理

修改HTTP Method 暂时还未支持

**Comment by Medicean** [comment]
还可以参考这篇文章

https://xz.aliyun.com/t/6917
