### ISSUE TITLE
jsp链接数据库 密码带%号特殊字符无法连接

### ISSUE THREAD

**Issue by qwezxc8080** [AntSwordProject/antSword#291]
jsp链接数据库 密码带%号特殊字符无法连接 #
<img width="197" alt="屏幕截图 2021-08-29 151349" src="https://user-images.githubusercontent.com/89723294/131242021-ab28dc82-5930-4280-b469-9a844f921878.png">

**Comment by Medicean** [comment]
`%` 改成 `%25`
