### ISSUE TITLE
浏览器能访问，antsword连接失败，一片红，菜刀直接连接成功。不知何故。

### ISSUE THREAD

**Issue by werwolfz** [AntSwordProject/antSword#296]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [x] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

---

## 新功能建议

- [x] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [x] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

---

### shell 连接 Bug

1. 服务端操作系统

2. 服务端shell代码

3. 服务端环境配置

4. 客户端连接配置

**Comment by werwolfz** [comment]
主机环境：360杀毒、安全狗、实时保护全都已经关闭。木马已经免杀，浏览器执行whoami成功。antsword连接测试一片红，测试一个没有任何防护的主机连接没问题。 遂我用菜刀连接立马成功。 非常确定这是antsword的一个bug或代码问题。谢谢。

**Comment by Medicean** [comment]
@werwolfz 请填一下 ，方便复现

服务端操作系统
服务端shell代码
服务端环境配置
客户端连接配置

**Comment by werwolfz** [comment]
win10
url后面传递php木马的密码，php马挺正常的。没有挂代理。
其他的不太记得了。


yzddmr6 ***@***.***> 于2022年1月18日周二 15:12写道：
