### ISSUE TITLE
勾选`忽略HTTPS证书`仍然出现`CERT_HAS_EXPIRED`的问题

### ISSUE THREAD

**Issue by yukar1z0e** [AntSwordProject/antSword#298]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [x] 我使用的操作系统是 ***macOS*** 12.0.1 M1 Chip
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [ ] 我使用的是 64 位操作系统
- [x] 我使用的是 Arm操作系统
### Bug 详细描述

使用M1芯片的Macbook时，连接某些使用https证书的web管理脚本时，会报错`CERT_HAS_EXPIRED`,按照处理方法将设置中`忽略HTTPS证书`勾选上，仍然发现同样的问题。
但是，使用windows 10 x64 操作系统链接同一使用https证书的web管理脚本时，在设置中`忽略HTTPS证书`勾选上，则可以成功链接，猜测该问题是仅出现在Arm架构的macos系统的bug。
---

**Comment by Medicean** [comment]
默认设置里的配置只会影响新加的Shell，已有的Shell配置不受影响。所以你应该查看一下你所说的Shell自己的配置。

操作方法，选中Shell 单击鼠标右键 ，选择编辑数据，在 其他设置 选项卡中，找到 忽略HTTPS 证书

**Comment by yukar1z0e** [comment]
已解决
