### ISSUE TITLE
2147217887:ODBC 驱动程序不支持所需的属性 --中国蚁剑 v2.1.14

### ISSUE THREAD

**Issue by qingguozth** [AntSwordProject/antSword#300]
![image](https://user-images.githubusercontent.com/41466845/144974057-800c6535-6b10-489e-9523-287e2d743e70.png)

![image](https://user-images.githubusercontent.com/41466845/144973958-3b906a8b-30c5-4e50-8e73-ac2229cef2e2.png)

![image](https://user-images.githubusercontent.com/41466845/144973992-d82952cb-669e-4de1-ad12-338576d77a18.png)

在中国蚁剑 `v2.1.14` 版本上执行`XP_CMDSHELL`命令时，报错 `2147217887:ODBC 驱动程序不支持所需的属性`。

在中国蚁剑 `v2.1.6` 版本上执行`XP_CMDSHELL`命令时，成功。

![image](https://user-images.githubusercontent.com/41466845/144974631-988e7bd4-156c-4471-968e-ec03794eee34.png)

![image](https://user-images.githubusercontent.com/41466845/144974661-11bb8267-6184-4769-91c3-c57e619f3885.png)

**Comment by yzddmr6** [comment]
什么类型的shell？

**Comment by qingguozth** [comment]
> 什么类型的shell？

asp的

**Comment by yzddmr6** [comment]
按照这个改一下看看有没有帮助
https://github.com/AntSwordProject/antSword/pull/241/commits/5acb55f87feaf1217b5560d8dfb7b2dd3002b772

**Comment by qingguozth** [comment]
> 

嗯嗯，修改后可以了，感谢

**Comment by qingguozth** [comment]
https://blog.csdn.net/Ca3tie1/article/details/103605485

**Comment by Medicean** [comment]
@qingguozth 贴一下 Shell 配置，注意把 URL 字段打码
