### ISSUE TITLE
蚁剑2.1.14，工具栏若存放过多插件，则插件无法删除

### ISSUE THREAD

**Issue by alem0n** [AntSwordProject/antSword#303]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [x] 我使用的操作系统是 ***Windows*** 10+

---

- [x] 我使用的是 64 位操作系统

### Bug 详细描述

蚁剑2.1.14，工具栏若存放过多插件，则插件无法删除，也无法选择超出屏幕范围的插件，“设置你要添加到工具栏的插件”按钮被挤到最右边。
建议将“设置你要添加到工具栏的插件”按钮放到最左边，可以暂时解决bug，但是依旧无法选择后面的插件。

---

**Comment by Medicean** [comment]
调整一下窗口大小即可。未来会考虑限制数量。

**Comment by Weltolk** [comment]
> 调整一下窗口大小即可。未来会考虑限制数量。

win10最新版下横向拉伸有上限,距离不够显示出来设置,不过我下面给出了一个方法

**Comment by Weltolk** [comment]
一个临时的解决方法:我是win10最新版,蚁剑和蚁剑的加载器也是最新版,我的蚁剑安装了很多插件,并且都在设置里开启了显示,此时显示的插件过多,把设置挤到了最右边,而且蚁剑的窗口横向拉伸有上限,即使横向拉到最大也显示不到设置,此时可以通过下述方法临时解决
1.查看一下插件显示栏最右边的插件名称
2.点击菜单栏的"调试"-"开发者工具",按ctrl+F搜索第1步记下来的插件名称
3.此时插件显示栏里的插件列表显示已经向右移动了
4.重复上述步骤直到"设置"按钮显示
