### ISSUE TITLE
插件市场存在bug

### ISSUE THREAD

**Issue by alem0n** [AntSwordProject/antSword#304]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [x] 我使用的操作系统是 ***Windows*** 10+

---

- [x] 我使用的是 64 位操作系统

### Bug 详细描述

因github默认分支改为main，所以插件市场判断插件是否安装成功的条件不能在单纯的以“master”作为标准，否则将会出现不能正确显示插件成功安装的bug。应该以“master”和“main”共同来判断。
---

**Comment by Medicean** [comment]
已知问题，感谢反馈，暂时仍会继续使用 `master` 作为标准，@antsword-store 中的所有仓库均有 `master` 分支，无需担心
