### ISSUE TITLE
MacOS 11.6.6 下，右键程序坞上的蚁剑图标，不能退出程序

### ISSUE THREAD

**Issue by Feiju12138** [AntSwordProject/antSword#307]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [ ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [x] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [x] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

- 我使用的操作系统是 **MacOS 11.6.6**
- 我使用了`Deeper.app`强制启动了以下程序坞的配置
  - 禁用修改程序坞的图标位置
  - 禁用修改程序坞的大小
  - 强制将最小化图标合并到应用程序图标
  - 强制将隐藏的应用程序的图标变成半透明

右键程序坞上的蚁剑图标，选择退出，不能退出程序，而是隐藏程序，但是可以使用菜单栏上的应用程序菜单中的退出（command+Q）来退出程序，也可以正常使用菜单栏的图标来退出程序

## 新功能建议

添加`启动或关闭菜单栏的图标`的设置

**Comment by Medicean** [comment]
重新更新一下代码，这次修复没有发版本

**Comment by Feiju12138** [comment]
@Medicean 大佬，求教如何打包成Mac的可执行文件，或者能不能发布一个小更新的版本

**Comment by Medicean** [comment]
> @Medicean 大佬，求教如何打包成Mac的可执行文件，或者能不能发布一个小更新的版本

不需要重新打包，你把 antsword 源码重新下载就行了，用 `git`同步代码也可以，或者 HTTP下载zip包直接覆盖也行。

**Comment by Feiju12138** [comment]
@Medicean 问题已解决，非常感谢
