### ISSUE TITLE
ignoreHTTPS is not a function

### ISSUE THREAD

**Issue by zsp00** [AntSwordProject/antSword#311]
## 报告 Bug
- [x] 我使用的操作系统是 ***Windows*** 10+

---
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

新增一个https错误的证书的网站时，添加不上！ignoreHTTPS方法不存在！superagent这个包里我看也没这个函数的支持啊，啥情况

![1655791910(1)](https://user-images.githubusercontent.com/8943617/174728924-ee4a338d-83f5-475f-8576-aed7dc38870f.png)

**Comment by Medicean** [comment]
node_modules 目录里的库是修改过的，不要自己随便修改已有的库。这个问题将在未来考虑解决
