### ISSUE TITLE
更新antSword-2.1.15后 数据库连接正常可是无法操作数据库，使用antSword-2.1.14 正常

### ISSUE THREAD

**Issue by arkizat** [AntSwordProject/antSword#319]
![image](https://user-images.githubusercontent.com/31034913/182560390-9d20df37-2938-47ea-9759-3bf1c59ca24f.png)
用2.1.14版本正常，重新下载加载器和2.1.15源码有运行还是一样的

**Comment by laogavip** [comment]
跟我一样  我也是这样

**Comment by Medicean** [comment]
已修复，直接更新代码即可
