### ISSUE TITLE
v2.1.15版本不支持Linux

### ISSUE THREAD

**Issue by wuerror** [AntSwordProject/antSword#325]
- [ ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [ ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***Debian/kali*** GNU/Linux

---
- [ ] 我使用的是 64 位操作系统

### Bug 详细描述
下载release包，将旧目录中的antData目录放入新目录，在重新打开。显示初始化成功，但是重新打开就报错
![image](https://user-images.githubusercontent.com/24793908/203278204-39642931-9d99-4d68-aa6a-2c42f867ec18.png)

**Comment by Medicean** [comment]
mime 库目录的大小写问题

```
cp -a node_modules/mime node_modules/Mime
```

**Comment by wuerror** [comment]
> mime 库目录的大小写问题
> 
> ```
> cp -a node_modules/mime node_modules/Mime
> ```

试了一下没用，报错内容没变

**Comment by Medicean** [comment]
https://github.com/AntSwordProject/antSword/blob/3faa3beb2906c0a206a04b7053254dea6348d9c6/node_modules/mime/index.js#L3

出错的地方就是这里，手动进这个库的目录里面去修一下吧

**Comment by wuerror** [comment]
> https://github.com/AntSwordProject/antSword/blob/3faa3beb2906c0a206a04b7053254dea6348d9c6/node_modules/mime/index.js#L3
> 
> 出错的地方就是这里，手动进这个库的目录里面去修一下吧

感恩，有效的
