### ISSUE TITLE
antSword-2.1.15 php webshell 查询数据库报错

### ISSUE THREAD

**Issue by Pet36** [AntSwordProject/antSword#329]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [x] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [x] 这是一个新功能的建议
- [x] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑
---

## 报告 Bug
- [x] 我使用的操作系统是 ***Windows*** 10+
---
- [x] 我使用的是 64 位操作系统

### Bug 详细描述
shell连接正常
数据库打开也正常
执行sql语句时卡住不动
启动调试时报如下错误
### 数据库查询 Bug
![123](https://user-images.githubusercontent.com/103318626/208926773-5d0cacd2-0bc5-4117-9a01-d7bdb7dfd7a6.png)

**Comment by Medicean** [comment]
Fixed in [3faa3be](https://github.com/AntSwordProject/antSword/commit/3faa3beb2906c0a206a04b7053254dea6348d9c6)
