### ISSUE TITLE
关于base64出现的一些报错

### ISSUE THREAD

**Issue by Iceqaq** [AntSwordProject/antSword#333]
版本 2.1.15

shell如下
![image](https://user-images.githubusercontent.com/43596990/221352051-a95603aa-0c8a-496a-88be-b467ef05a450.png)

base64连接，报错
![image](https://user-images.githubusercontent.com/43596990/221352072-6b785fd7-5ac6-4a0b-a0da-7618dadd88a4.png)

其余连接均可
![image](https://user-images.githubusercontent.com/43596990/221352087-90f28b5f-c4b0-4aa0-a337-8bc5e1ed0ab6.png)

自写一个编码器测试一下
什么代码都没有
![image](https://user-images.githubusercontent.com/43596990/221352117-18d788db-5aca-4eee-82b4-847903eddb95.png)
返回空，没有什么问题
![image](https://user-images.githubusercontent.com/43596990/221352138-e8acef99-8bb8-48fa-9c55-7de13ff70cae.png)

新增了一行代码base64
![image](https://user-images.githubusercontent.com/43596990/221352163-7b70b1a3-b17d-4032-923c-36a622a6aba3.png)
发现又出现了报错
![image](https://user-images.githubusercontent.com/43596990/221352174-16649e83-f74b-4c07-a140-9fc4100418a3.png)

随便写一个，如下所示
![image](https://user-images.githubusercontent.com/43596990/221352210-dbb52570-a2f5-46ba-8afe-d53b8708de7b.png)
![image](https://user-images.githubusercontent.com/43596990/221352219-97d61762-174d-4efe-b8dd-47caeb9964c6.png)

**Comment by Medicean** [comment]
检查目标环境 phpinfo, 看 disable_function 里面有没有禁止 `base64_decode`

**Comment by Iceqaq** [comment]
> 检查目标环境 phpinfo, 看 disable_function 里面有没有禁止 `base64_decode`

并没有,师傅
![image](https://user-images.githubusercontent.com/43596990/221530991-1f90b19c-a0c3-4f3d-8f6d-873c47a2899b.png)

**Comment by Iceqaq** [comment]
> 
无法发包，流量不会到burp，这也就是我没调试出问题的原因。

**Comment by Medicean** [comment]
我这边测试是正确的。你打开 开发者工具看一下 具体是什么报错。
![image](https://user-images.githubusercontent.com/6082020/221753101-9b10bf15-7ba3-49da-8e9f-3d6a9b32bf7c.png)

![image](https://user-images.githubusercontent.com/6082020/221753001-6500bfd1-c761-4c88-b528-b4aedbed51f8.png)


另外再检查一下你本地的这个文件是不是被篡改了
https://github.com/AntSwordProject/antSword/blob/master/source/core/php/encoder/base64.js

**Comment by Iceqaq** [comment]
你好，不好意思师傅，经过排查发现是被电脑的赛门铁壳拦截了
原因是本地PC赛门铁壳拦截了base64，但是却没有拦截default，和其他的任意自带编码，所以一开始没有找到。

**Comment by Medicean** [comment]
了解了～
