### ISSUE TITLE
数据导入功能

### ISSUE THREAD

**Issue by antoor** [AntSwordProject/antSword#37]
能直接把菜刀的数据库导入到中国蚁剑。

> from [http://uyu.us/#/guest](http://uyu.us/#/guest)

**Comment by Medicean** [comment]
`node.js` 操作 `Access` 数据库难度有些大，找了一下发现很多都是直接调用 `ActiveX` 来实现的，意义不是很大。或许可以考虑其它语言来过渡？

**Comment by antoor** [comment]
@Medicean 方便的话可以直接写windows下使用的脚本处理即可（因为导入菜刀数据的话，应该都有windows环境吧？
然后就是nodejs跨平台操作access，我直接尝试处理buffer，可以解析出url&&pwd，但是格式很乱且并不是都能完整获取完毕，所以暂时还没啥好办法

**Comment by Medicean** [comment]
原来的菜刀在 win 下，现在要在类 Unix 系统下使用，这种情况应该是普遍存在的。不过 node.js 操作 Access 实在是很鸡肋。 @antoor

**Comment by antoor** [comment]
@Medicean 哈哈，其实不用太纠结的，可以暂时出个win版，就像目前的在线更新不支持win一样。。
蚁逅总会有办法的
 ![](https://40.media.tumblr.com/9f12e4cb27a34faba2883a7beef9b72b/tumblr_o5fsf5MPnj1spqhdqo3_400.jpg)
