### ISSUE TITLE
对蚁剑改进的一些初步建议

### ISSUE THREAD

**Issue by loveshell** [AntSwordProject/antSword#5]
蚁剑是个非常不错的网站管理工具，毋庸置疑～
个人使用过程发现一些小的问题，整理如下，希望对蚁剑的体验改进有所帮助
- 分类需要支持重命名
- shell列表搜索功能，最好直接对添加数据进行全文搜索
- 命令console不能粘贴数据，同时命令可以tab更好了
- 考虑后续客户端升级，数据库和配置文件在哪里？是否需要定义出来。我看现在使用的是nedb，那么是否考虑数据导出为配置，以便下次升级使用？

**Comment by antoor** [comment]
感谢你的支持！
首先我对你的一些建议进行解答吧：
1. 分类重命名以及其他一些小细节功能，因本人精力有限 不能一下子就完善这么多，当然以后也会慢慢增加改进的，也希望能有人一起参与开发；
2. 搜索功能同上，UI之前已经写好，具体的实现代码没来得及写；
3. 由于采用的框架原因，终端控制台只支持英文输入以及一些快捷键无法使用，这个已经在考虑更换的范围，tab功能是必须有的啦！慢慢来！
4. 用户的数据以及缓存，在osx、linux下保存在用户主目录/.antSword中，windows下在用户root目录中，好像进入%ROOT%目录就可以看到了，客户端升级的时候不需要考虑数据，直接删除旧版启动新版即可～

还有其他的一些小问题，总结起来现在能给的答案就是：时间忙。。慢慢来。。哈哈！
再次感谢你的支持呀！祝玩得愉快~

**Comment by loveshell** [comment]
希望也能增加user-agent自定义功能

**Comment by antoor** [comment]
@loveshell 本来就是可以自定义HTTP参数以及数据的，详见：`modules/request.js`

**Comment by loveshell** [comment]
嗯，我之前有改过这里。
主要这样的话每个使用者都需要每次独立修改编译，考虑到属于通用性功能，所以希望能够在工具的设置部分增加该功能，以便所有人使用

**Comment by antoor** [comment]
这个可以有，开始之前数据发包处理函数是写在前端，但是这样的话就极容易引起页面崩溃，所以放到了后端，也便更容易处理buffer。
- - -
> 功能实现起来并不难，我有空再加上-U&U-

**Comment by Medicean** [comment]
issue 中所提到的功能已经在目前版本中全部支持。故关闭此 issue
