### ISSUE TITLE
C盘目录无权限显示的Bug + 文件管理内增加查找功能

### ISSUE THREAD

**Issue by joerger** [AntSwordProject/antSword#51]
1,文件管理中，对于C盘无权限的目录会显示成文件，双击后会提示下载
![qq 20160503173618](https://cloud.githubusercontent.com/assets/19166122/14979544/a68a55b2-1155-11e6-9d55-28387eaf1ff7.jpg)

2.对于webshell连接类型建议增加一些，PHP,ASP,ASPX已经满足不了需求

3.建议增加代理功能

4.建议在文件管理内增加查找功能

5.建议插件中心内的插件可以采取收费的模式，不仅鼓励写插件的同学，也可以让更多的人加入到完善软件功能的工作中。

**Comment by Medicean** [comment]
@joerger  感谢反馈

1.  这个确实是存在，下个版本会修复 [+]。
2. 对于 Jsp, Python, Perl 等脚本，请使用 CUSTOM 模式，该模式为通用型的，如果你自己编写了相应的 CUSTOM 模式的 Shell 欢迎提交到 [shells 目录](https://github.com/antoor/antSword/tree/master/shells)下。
3. 代理功能自 v1.1.0 就已经支持，详见 #23 。
4. 文件管理内查找文件功能将会在会续版本中开发，敬请期待[+]。
5. 剧透一下，插件功能将会在 v2.0 版本中发布

**Comment by joerger** [comment]
如果能增加上传内页功能绝对可以秒杀国内webshell管理功能，不知道大神有没有考虑呢？ 
顺便问下能QQ红包赞助吗，赞助不多感谢作者奉献！！！

**Comment by joerger** [comment]
还存在一个CMD乱码问题，测试发现，如果执行正常的命令会返回乱码，但是如果执行错误的命令，CMD会返回正常的中文报错，返回中文报错后再执行正确的命令将会返回中文的结果，测试如下！

![qq 20160503221603](https://cloud.githubusercontent.com/assets/19166122/14986067/eff6f7f6-117c-11e6-9cda-888c6afe830f.jpg)

**Comment by Medicean** [comment]
乱码问题，可以参考 #8 

至于你说的 “上传内页”，听不懂你在说什么，可以具体解释一下吗?

**Comment by antoor** [comment]
@joerger  目录无权限读取文件这个问题，可以试试在地址栏输入绝对路径进入，然后就是shell服务端脚本类型，这个是可以自定义扩展的，只不过暂时还没时间完善文档。 不过如果你有兴趣，研究一下会发现非常容易的。
![](http://img.hb.aicdn.com/be667787998cd5e47c52cecbbbabb8121213a05a16009-8bNCVb_fw658)

**Comment by joerger** [comment]
@antoor  复制文件夹名称，通过绝对路径访问可以正常访问！！！

**Comment by joerger** [comment]
@Medicean   关于内页上传就是定义好模板编辑好变量轮询生成html的页面上传，你可以参考xise这个webshell管理软件，目前是国内写的最成熟的一款了，这是我分享的一个下载链接：http://pan.baidu.com/s/1i5MxRet

这款软件有几个地方可以借鉴一下

1.智能识别webshell类型
![qq 20160504092343](https://cloud.githubusercontent.com/assets/19166122/15003022/fb421d5e-11d9-11e6-8b67-f71e1a0cf5ba.jpg)

2.测试目录权限
![qq 20160504092457](https://cloud.githubusercontent.com/assets/19166122/15003045/2936fe50-11da-11e6-99ec-918b4cb17260.jpg)

3.打开网页（比较方便）
![qq 20160504092629](https://cloud.githubusercontent.com/assets/19166122/15003068/5f1c3364-11da-11e6-8858-4ffb8e24479c.jpg)

4.生成内页（一个神奇的功能 ^_^ ）

![qq 20160504092741](https://cloud.githubusercontent.com/assets/19166122/15003082/8e2d039a-11da-11e6-9740-c20dc5337607.jpg)

**Comment by joerger** [comment]
进入到无权限的目录会提示打开失败并提示报错，但是状态会一直持续，不会自动结束。

![qq 20160504142636](https://cloud.githubusercontent.com/assets/19166122/15006505/48187dd8-1204-11e6-8b58-6515e34b4f02.jpg)

**Comment by Medicean** [comment]
@joerger 

> 中国蚁剑是一款开源的跨平台网站管理工具，它主要面向于合法授权的渗透测试安全人员以及进行常规操作的网站管理员。

像你上面提到的挂内页的操作，正常网站管理中不会使用到该功能，倒是黑色产业当中对该功能需求比较大，经过讨论，决定不采纳该建议，还是感谢你的建议。

**Comment by joerger** [comment]
@Medicean   关于之前的代理问题看了一下相当于是PrProxy之类的代理，后面的插件是否会考虑整合lcx反弹代理功能呢，因为在做WEB测试的时候经常会遇到一些内网IP的网站，渗透内网的时候可能又要去上传一些代理的大马比较麻烦并且会出现windows与linux的区别上传多个，我个人比较笨的思路是蚁剑中有一个目录存放2个反弹大马（windows以及linux），软件在右键的时候有代理选项，选择代理会自动上传该大马（大马中反弹的IP以变量的给到），上传后会弹出对话框输入反弹的IP，输入确定后会自动替换变量的值并弹出访问的绝对路径，可能比较麻烦不过这个功能还是比较实用和方便。

**Comment by Medicean** [comment]
@joerger 反弹shell功能不属于核心功能，暂时不会考虑，2.0 版本中会以插件形式开发。

**Comment by Medicean** [comment]
@joerger 经过测试，如果没读取的权限会直接提示拒绝。没能复现你说的这种情况。你检查一下你的 AntSword 是不是最新的。

如果可以，能否通过蚁剑交流群联系一下我，提供一下你的环境呢？

**Comment by Medicean** [comment]
文件管理内现已支持快速跳至按键首字母所在行  9f32a6c6b2e

基本上这个 issue 可以关闭了
