### ISSUE TITLE
关于数据库和虚拟终端的一些建议

### ISSUE THREAD

**Issue by intosec** [AntSwordProject/antSword#52]
1.数据的导出
2.不同数据库常用命令的模板功能，例如根据不同数据库类型，把exec xp_cmdshell ‘’之类的语句放到一个模板文件里，在命令窗口那添加一个下拉框，选中后自动填入命令框。
3.命令框的命令执行快捷键。例如输完命令后直接按Alt+Enter就能执行命令，避免多余的鼠标操作。
4.另外就是，当前会话中执行过的命令如果能像cmd那样使用上下方向键选择就更方便了。
5.虚拟终端的命令执行功能有缓存，相同的命令第二次执行时，返回结果无变化，这个功能对某些命令不太合适，例如netstat，本身需要用来查看最近的连接状态，如果存在缓存会误导用户。

PS:这个项目真的是太让人惊艳了，用户体验比其他类似项目好太多了，未来必然是人手一份的神器。2.0什么时候能发布，我已经开始学习nodejs了。

**Comment by antoor** [comment]
**感谢建议，最近在抽空完善2.0，预计发布时间为6月6日，欢迎关注微博动态了解！**

1. 数据的导出这一块，很多人都提到过，但是由于`access`数据库暂时无法在跨平台上进行驱动操作，所以现在仍保留在todo list，当然我们也欢迎对这方面有经验的朋友能给我们提供点思路😁

2. 关于数据库模块，现在还有很多待完善到地方，比如你所提到到常用命令补全，还有数据导出、分析等，也暂时只能放在一边，等大体核心框架重构完毕再进行解决细节😋

3. 同上👆

4. 虚拟终端中是可以使用上下方向键进行历史命令选择的（目前版本也有很多优化的地方，比如中文输入、复制粘贴等😛

5. 确实是这样，后边会考虑给用户一个选择是否缓存数据的选项👀

总之，我们还有很多要完善的地方，不过也在慢慢地不断进步优化。    
**我们欢迎有兴趣的朋友一起参与开发，也非常感谢关注此项目等朋友们的点点滴滴建议，谢谢大家！**

![](http://hbimg.b0.upaiyun.com/d0e29c34ef5177d341988a6947f07f41e960703f787af-1g9sJI_fw658)

**Comment by Medicean** [comment]
逐条回复当前进度：

1.数据导入、导出功能，已经在 CopyShell 和 ImportShell 插件中支持：
 https://github.com/AntSword-Store/CopyShell
 https://github.com/AntSword-Store/ImportShell

2.将在未来考虑支持
3.虚拟终端在输入完命令后，按Enter就可执行命令
4.支持命令历史和部分常用命令补全功能
5.缓存管理选项已支持，编辑 shell=>其它设置

:)
