### ISSUE TITLE
通过shell上传文件功能有问题，给出修复建议

### ISSUE THREAD

**Issue by jjf012** [AntSwordProject/antSword#97]
filemanager\index.js
640行
`const fileName = f.substr(f.lastIndexOf('/') + 1);`
改为
`const fileName = f.substr(f.lastIndexOf('\\') + 1);`
664行也是一样将`\`改为`//`，然后可以正常上传了。
因为获取到的路径是`C:\\Users\\test\\Documents\\\xb0\xb2\xd7\xb0\xcb\xb5\xc3\xf7.txt`，用`/`截取不到。

**Comment by Medicean** [comment]
确实在 windows 客户端下存在这个问题，感谢 👍
